### ISSUE TITLE
Adjust java client samples to new home

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-docs#1001]
See https://forum.camunda.io/t/zeebe-git-examples-unaccessible/38459 - the examples have moved to https://github.com/camunda-community-hub/camunda-8-examples

Need to update links in https://docs.camunda.io/docs/apis-clients/java-client-examples/process-instance-create/ etc...

See this issue for further background: https://github.com/camunda/zeebe/issues/9500

**Comment by akeller** [comment]
@berndruecker are you adjusting this or should @christinaausley look into it?

**Comment by berndruecker** [comment]
Created https://github.com/camunda/camunda-platform-docs/pull/1007 - feel free to merge it after review (not sure if we need a review really for everything and don't want to add more wine to the bill ;-))
