### ISSUE TITLE
Replace the GIF with a text description on the "How to model a diagram" page

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#1048]
The demo animation in https://docs.camunda.io/docs/components/modeler/bpmn/ should be updated, showcasing the new Desktop or Web Modeler, including all new actions (i.e. multi-select, alignment).

Is this urgent? No. Modeling itself is quite self-explanatory. But we shouldn't have something that is outdated for too long on the docs.

**Comment by akeller** [comment]
@christian-konrad, I'll have more thoughts on this in my updated [Docs Vision 2.0](https://docs.google.com/presentation/d/122T4xcwOejuFbhQu0KpoAzL-rwCkaX6bUirym3IL_DE/edit?usp=sharing), but I'm likely going to advocate for removing GIFs from the docs for accessibility reasons. 

When you say "modeling itself is quite self-explanatory," is there anything you feel we would need to add to substitute high-quality text instead of this kind of gif experience?

**Comment by volodymyr-melnykc** [comment]
@akeller I'd like to follow up on this issue. The documentation page like ["BPMN in Modeler"](https://docs.camunda.io/docs/components/modeler/bpmn/) has an animated GIF (which is also outdated). 
What are our guidelines for creating documents? Do we want to use GIFs? In the preview comment, you mentioned that GIFs can be not good for accessibility reasons.

**Comment by akeller** [comment]
Hi @volodymyr-melnykc, my stance on GIFs remains—they are difficult to maintain and, for accessibility reasons, should have the ability to pause/start/stop, which we don't have built into our documentation framework. We should prioritize high quality text descriptions, and where it makes sense, provide screenshots that can be updated (I believe the Modeling team has [screenshot automation](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#screenshot-automation))

I recommend we remove the GIF and replace it with text. DevEx can remove these GIFs and draft text for you to review if you'd like, but we would prioritize it against our epic delivery and may not get to it soon.

**Comment by akeller** [comment]
@christinaausley I assigned this to you, note the recent messages above - this isn't a high priority but could be considered a quick win.

**Comment by christinaausley** [comment]
It looks like we are only discussing the gif [here](https://docs.camunda.io/docs/components/modeler/bpmn/#demo). As an FYI, we also have gifs [in the primer docs](https://docs.camunda.io/docs/components/modeler/bpmn/bpmn-primer/#modeling-bpmn-diagrams), [DMN](https://docs.camunda.io/docs/components/modeler/dmn/#demo), and [token simulation](https://docs.camunda.io/docs/components/modeler/web-modeler/token-simulation/).

Within the scope of this issue, are we solely looking to update https://docs.camunda.io/docs/components/modeler/bpmn/#demo? I'll go ahead and launch a PR for that. While I'm here, do we want to remove any other gifs and replace with text?

CC @volodymyr-melnykc @akeller @christian-konrad

**Comment by christinaausley** [comment]
https://github.com/camunda/camunda-docs/pull/4125 Launched within the scope of the original issue here.

**Comment by akeller** [comment]
> Within the scope of this issue, are we solely looking to update https://docs.camunda.io/docs/components/modeler/bpmn/#demo? I'll go ahead and launch a PR for that. While I'm here, do we want to remove any other gifs and replace with text?
> 
> CC @volodymyr-melnykc @akeller

I would need to go through the docs and compare them with the current product experience, which I need to carve off time to do. I'm ok to remove these as we encounter them or get feedback they are out of date.
