### ISSUE TITLE
Embedded codeblocks

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#1127]
> https://github.com/saucelabs/docusaurus-theme-github-codeblock

> @pepopowitz good backlog item & partnering with @christinaausley to find where we could use it today, then make it available to our engineers for future docs. 

> In fact, I see this helping to solve our accessibility issue with BPMN diagrams by embedding the XML. Maybe as a toggle or tabbed experience? 🤔 I'll create a new issue here.

_Originally posted by @akeller in https://github.com/camunda/camunda-platform-docs/issues/1078#issuecomment-1208503422_

**Comment by akeller** [comment]
This is maybe not as granular as it looks -

1.  Add Plugin (tiny 🦔  for @pepopowitz )
2. Find current use cases (?? for @christinaausley & @pepopowitz)
3. Find new use cases like BPMN diagrams (?? for @christinaausley & @pepopowitz)
4. Write implementation docs and let engineering know it's available (tiny 🦔 for @christinaausley or @pepopowitz)

**Comment by akeller** [comment]
FEEL code is marked as JS, which may not actually be the best way to handle this either. If possible we should mark FEEL as FEEL but that may be out of scope for this particular issue.

**Comment by christinaausley** [comment]
I'd be happy to look into current use cases and new use cases and document these instances. Then, @pepopowitz and I can consult and combine efforts to document implementation docs?

**Comment by akeller** [comment]
@pepopowitz was targeting this as a potential Q4 topic, but you can do that as pre-work to support this!

**Comment by christinaausley** [comment]
Awesome! In that case, I'll let @pepopowitz handle this. Let me know if/where I can assist!

**Comment by akeller** [comment]
Could help us solve #1046 via XML presentation.

**Comment by akeller** [comment]
Similar to https://github.com/camunda/camunda-docs/pull/3155

**Comment by pepopowitz** [comment]
#3155 was closed, in favor of #3281. 

I think that #3281 fully addresses this issue. @akeller let me know if you think otherwise.

**Comment by akeller** [comment]
I'm good with this! Thank you @pepopowitz!
