### ISSUE TITLE
Investigate SEO for current docs version

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#1143]
In https://github.com/camunda/product-hub/issues/232 we learned all sorts of things about SEO & versioned documentation. We should apply those findings to the C8 docs, to avoid reliving that painful experience.

## Acceptance criteria

* Only the current version (`8.1` for now) should be indexed and searchable from Google. 
  * #1905 describes [an example URL](https://docs.camunda.io/docs/0.26/reference/bpmn-workflows/multi-instance/)
* Internal search should clearly mark what version, if multiple versions show up in the search results.
* Identified work is based on best practices learned in https://github.com/camunda/product-hub/issues/232.

## Included work
- [x] https://github.com/camunda/camunda-platform-docs/pull/2112: Sitemap should include only the supported version(s) of docs
- [x] https://github.com/camunda/camunda-platform-docs/pull/2121: tag, links, and unsupported versions removed from sitemap
- [x] #2577: Old versions of docs should emit a `link rel=canonical` pointing at the current version of the docs (the URL with no version in it)

## Background

`camunda 8 bpmn coverage` in Google returns `https://docs.camunda.io/docs/0.25/components/zeebe/bpmn-workflows/bpmn-coverage/` as the first hit. (update: this example now links to the versionless URL, which is correct.)

Algolia docsearch returns `https://docs.camunda.io/docs/0.26/reference/bpmn-workflows/bpmn-coverage/` with similar search terms (although I could not reproduce this).

**Comment by akeller** [comment]
Today, much to my chagrin, I found Google linking to a `1.3` page.

We'll need to spend some time user-designating canonicals before we end up in a situation like our C7 docs.

**Comment by akeller** [comment]
Thanks for your updates here @pepopowitz!

**Comment by akeller** [comment]
#2112 may fix this

**Comment by pepopowitz** [comment]
> #2112 may fix this

It didn't, but 🤞 that #2121 does!

**Comment by akeller** [comment]
#2121 is live and the sitemap correctly shows only supported versions of the product.

But Amara, this would still be incorrect, wouldn't it?

Amara and Steven have some paranoia about accidentally doing something to completely sabotage the SEO, so Amara started pairing down what was in the sitemap by removing unsupported/unmaintained versions first. 

Very specifically, I'm trying to look for any older versions to be removed from top 100 landing pages in Google Analytics like `/docs/0.26/reference/bpmn-workflows/multi-instance`. If this page is not removed by the changes to the sitemap, I will look for areas where this is linked directly. This is not a good entry point for any user to the C8 docs experience.

**Comment by akeller** [comment]
The sitemap should be only current version docs now.

I'm watching Google Search Console to verify things are how we want them 🤞

**Comment by akeller** [comment]
Excluded by robots.txt 💪 Thank you @pepopowitz! 

![Image](https://github.com/camunda/camunda-platform-docs/assets/1051363/261c566c-3cd3-4851-a230-981fdb408a91)

**Comment by akeller** [comment]
Re: canonicals - https://stackoverflow.com/questions/75362070/can-i-have-canonical-links-that-show-to-latest-version

**Comment by akeller** [comment]
Is this the best/easier solution for one-offs? https://github.com/facebook/docusaurus/issues/2603

**Comment by akeller** [comment]
I'm reasonably happy about how things look, and I don't plan to shift more time/attention to monitoring SEO. I will move this back into `Ready` and remove myself from the assignment since the only remaining piece is the canonical work.
