### ISSUE TITLE
Find way to sync FEELdocumentation into the cloud documentation

### ISSUE THREAD

**Issue by pihme** [camunda/camunda-docs#136]
The cloud documentation now contains a chapter FEEL in the references section.

The source for this documentation lives in a different repository: https://github.com/camunda/feel-scala

The copied contentis a subset of the documentation in the FEEL repo. What is missing is the FEEL developer guide. This developer guide is only relevant if one would want to integrate the FEEL engine into ones own software. For users of Camunda Cloud or Zeebe community edition the content is not relevant.

The content in the FEEL repository is at the time of this writing also pending PR https://github.com/camunda/feel-scala/pull/218

Afterwards, we should look for a way to automatically sync the two documentation repositories.

To that end, this repo imports the FEEL sidebar content into its structure:

```
    },
    require("./docs/reference/feel/sidebar-schema"),
    "reference/glossary",
  ],
```

So the idea is that this sidebar-schema file could be maintained in the FEEL repository, and we write a script to copy the content we need from there.

The idea still needs to be discussed with @saig0 who is the maintainer of the FEEL repo.

**Comment by akeller** [comment]
Are we still interested in moving this forward? @menski your thoughts here?

**Comment by akeller** [comment]
Are we still interested in moving this forward? Is this something we could brief @pepopowitz and hand-off to him?

**Comment by saig0** [comment]
Yes. I'm still open to suggestions. 
The current copy&paste solution works but we could improve.

**Comment by akeller** [comment]
Doing some backlog cleanup.

**Comment by saig0** [comment]
I have a simple solution to solve this issue: 
- Use the C8 docs as the only source of the FEEL docs 
- Remove the FEEL language guide from the [FEEL-Scala docs](https://camunda.github.io/feel-scala/docs/reference/language-guide/language-guide-introduction). Instead, link to the C8 docs.

I created an [issue](https://github.com/camunda/feel-scala/issues/626) in the FEEL-Scala repo to track the work. There is something to do in the Camunda documentation. :rocket:

**Comment by megglos** [comment]
@akeller given the recent activity I assume this is still valid and handled by you and @saig0 going forward?

**Comment by saig0** [comment]
Done. :rocket: The language guide was removed from the FEEL-Scala docs.
