### ISSUE TITLE
What should we do with old redirect rules?

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#1397]
We should develop an official strategy for old redirect rules in the .htaccess file. 

Conversationally @akeller and I have talked about how we don't care too much about redirecting for pages in old versions of the docs, as we want to nudge people to update to the latest version. We've also talked about how we don't care much about redirecting pages in the `next` version, because those docs are to be considered under construction. 

Formalizing a strategy would: 

* Give us something to point at when people ask what our strategy is
* Give us guidance on when to skip or delete rules from the .htaccess

**Comment by akeller** [comment]
Similar to #1040.

**Comment by akeller** [comment]
I will move this into `Ready` and get a draft brewing for the strategy piece.

**Comment by pepopowitz** [comment]
@akeller I believe I've communicated a strategy in [the htaccess file](https://github.com/camunda/camunda-docs/blob/main/static/.htaccess), with comments. As long as people add htaccess rules to the corresponding version of introduction, then I am able to remove them when I archive a version.

I'm removing myself from assignee on this issue; if there's any other documentation you want to add in other places, I support it.

**Comment by akeller** [comment]
Let's close this out, thank you @pepopowitz!
