### ISSUE TITLE
Message Events Process is confusing for users

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-docs#146]
Copied over from the Zeebe repo: https://github.com/zeebe-io/zeebe/issues/4422

**Description**

The process shown at [Message Events](https://docs.zeebe.io/bpmn-workflows/message-events/message-events.html) is a bit confusing, since it seems the service task is directly completed and we wait until we receive a message which tells us that the money was collected.

We should try to re-model this process.

Related Zeebe Forum post 

https://forum.zeebe.io/t/is-the-zeebe-task-blocking-or-synchronous/1183

**Comment by akeller** [comment]
@menski can you move this forward please?
