### ISSUE TITLE
Operate REST API - Add enum values for state, type etc. for all object schemas

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-docs#1486]
The documentation lacks of an overview of possible values for enumerated values. That makes it difficult to create queries if one does not know which values are valid.
https://docs.camunda.io/docs/apis-clients/operate-api/#object-schemas 

This applies to:

- Process Instance
  - state
- Incident
  - state
  - type
- Flownode Instance
  - type
  - state

### Test case: 
[Operate REST API have enum values for state, type etc, for all object schemas](https://camunda.testrail.com/index.php?/cases/view/70456)

**Comment by akeller** [comment]
@aleksander-dytko are you aware of this?

**Comment by aleksander-dytko** [comment]
@akeller thanks for mentioning me. I'll add it to the operate board.

**Comment by johanwelgemoed** [comment]
@McAlm Just a quick question, if you run Operate instance you can access the swagger UI and there it lists everything, with examples. The docs page does not have the same level of detail as swagger.

**Comment by johanwelgemoed** [comment]
@aleksander-dytko we propose to rather remove this chapter from the docs since the information is in swagger (which will always be up to date). The docs are created manually and does not add any extra value at this point.

**Comment by McAlm** [comment]
@johanwelgemoed: swagger-ui indeed is an option for developers, but still, it does not list everything, e.g.:
<img width="368" alt="Bildschirmfoto 2022-11-11 um 19 37 33" src="https://user-images.githubusercontent.com/2012154/201408626-64405c71-8f31-47ad-b8cf-30998f58de25.png">

As developer I need to know which valid enum values are possible.

**Comment by aleksander-dytko** [comment]
@johanwelgemoed based on the discussion, I would propose to document everything in Swagger (as @McAlm suggested) and add the reference in the documentation. 

@akeller would that work for you from docs POV?

**Comment by akeller** [comment]
Yes!! I absolutely want to get away from manual, text-based API reference docs.

**Comment by johanwelgemoed** [comment]
Swagger UI will now show the enums for the types as mentioned in this issue. For example:
![Screenshot 2023-08-28 at 16 50 25](https://github.com/camunda/camunda-platform-docs/assets/112612181/c43e93eb-4387-45b3-a03c-d530d3640557)

This is being merged and will be part of the next patch releases for 8.1.x, 8.2.x as well as 8.3.0-alpha5 (2nd week of September)

@akeller Is this sufficient for now to close this?

**Comment by akeller** [comment]
@johanwelgemoed this sounds great and would meet my expectations for this issue.

**Comment by johanwelgemoed** [comment]
Pull requests merged
master: https://github.com/camunda/operate/pull/5180
8.1: https://github.com/camunda/operate/pull/5200
8.2: https://github.com/camunda/operate/pull/5201

**Comment by pepopowitz** [comment]
I believe this issue should be closed, due to the Operate REST API docs now being generated directly from the OpenAPI spec. 

An example (from https://docs.camunda.io/docs/next/apis-tools/operate-api/specifications/search-1/): 

![image](https://github.com/camunda/camunda-docs/assets/1627089/9b7ec27e-5f47-45ac-8f31-443333135793)
