### ISSUE TITLE
Identity - which permissions to add

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-docs#1503]
https://docs.camunda.io/docs/self-managed/identity/user-guide/adding-a-permission/ 

the docs say:
`Each component within the cloud stack has support for specific permissions. We recommend checking the [documentation for the required component](https://docs.camunda.io/docs/components/) to find out the list of permissions it supports.`

the link mentioned above is just heading to an overview of all apps but then it is difficult, if possible at all, to find the set of permissions needed. 

As a user I want to have a clear overview of the permissions per application as a table.

**Comment by akeller** [comment]
@dlavrenuek can you review and help me understand how we could change this to meet the needs of users working with Identity? Are the permissions dramatically different for each component? Or maybe recommended permissions?

**Comment by dlavrenuek** [comment]
@McAlm @akeller I agree that the current permission management is confusing and so are the docs. Identity will already create all possible permissions for C8 apps without the need for manual user interaction. The current permissions only limit the top level access to the apps and we are working on [resource based permissions](https://github.com/camunda-cloud/identity/issues/1218) where the users will be able to manage permissions to specific processes. We are currently discussing disabling the current permission management (read only mode) and will update the docs when the changes have been implemented on our side.

**Comment by akeller** [comment]
@dlavrenuek, what's the status of this? If there is still work to be done can you add it to the relevant Identity team/project board?
