### ISSUE TITLE
Many dependencies missing during tasklist-api-tutorial

### ISSUE THREAD

**Issue by mfmanca2000** [camunda/camunda-docs#1718]
Just running _npm install -g @nestjs/cli_ was not enough for me to complete the tasklist-api-tutorial.
I had to install nestjs/common, nestjs/core, typescript, lodash, webpack.

## Implementation notes

There are probably 2 parts to this: 

1. Updating [the docs](https://docs.camunda.io/docs/apis-clients/tasklist-api/tasklist-api-tutorial/) to call out any other dependencies that need to be installed
2. Updating [the example repo linked from the docs](https://github.com/camunda-community-hub/camunda-cloud-tasklist-api-nestjs/blob/4-application/package.json) to add the dependencies to the package.json, so that `npm install` will take care of them all.

**Comment by akeller** [comment]
Given that the GraphQL API will be deprecated in the near future ([as seen in the admonition](https://docs.camunda.io/docs/next/apis-tools/tasklist-api/tasklist-api-overview/)), we should consider removing this tutorial instead of updating it.

**Comment by christinaausley** [comment]
@jwulf Are you still working on this? Saw it was moved from the backlog to ready midyear, but wasn't sure if you planned on having it ready for review prior to release, or if I can assist 👍

**Comment by akeller** [comment]
Removing @jwulf as the assignee.

@christinaausley @pepopowitz does this roll into the work you are doing with API tutorials? Would also be good to check in with the Tasklist/HTO team on when this will be deprecated and removed.

**Comment by akeller** [comment]
This tutorial was deprecated in the 8.5 release. While it's still relevant for older supported versions, this API and tutorial was replaced with a REST API tutorial via https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/tasklist-api-rest-tutorial/. 

With that, I will close this issue.
