### ISSUE TITLE
Tasklist API fields lack detail

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#1722]
Originally surfaced in https://github.com/camunda/developer-experience/issues/29#issuecomment-1426048605

In the schema docs for the Tasklist API, there are a few fields that lack detail/context on _what kinds of values_ they can contain. 

Examples: [include directive](https://docs.camunda.io/docs/apis-clients/tasklist-api/directives/include/), [skip directive](https://docs.camunda.io/docs/apis-clients/tasklist-api/directives/skip/), and [claimTask.assignee](https://docs.camunda.io/docs/apis-clients/tasklist-api/mutations/claim-task/). In each of those cases, I don’t know what kinds of values to put in them. Examples would be helpful, or a more precise description of valid values.

cc @camunda/human-task-orchestration-dev

**Comment by akeller** [comment]
@pepopowitz is this still relevant after your work and collab with the API Explorers?

**Comment by pepopowitz** [comment]
Nope! Closing.
