### ISSUE TITLE
Document Elasticsearch Retention policy for Self-Managed users

### ISSUE THREAD

**Issue by korthout** [camunda/camunda-docs#1857]
Users who want to update to Elasticsearch 8 from 7 will encounter issues with the Elasticsearch Curator. To workaround this problem, Zeebe's 8.2 release of the Elasticsearch Exporter allows configuring an Index Lifecycle Management (ILM) Policy using the `retention` configuration options:

```yaml
retention:
  enabled: true
  minimumAge: 30d
  policyName: zeebe-record-retention-policy
```

This ILM Policy works on Elasticsearch 7 as well, and can function as a replacement of the Elasticsearch Curator for the indices created by Zeebe's Elasticsearch Exporter.

While this is a new feature of the Elasticsearch Exporter available from 8.2 onwards, it helps users upgrade the Elasticsearch instance in their Camunda Platform 8 Self-Managed cluster. We should document what changes users must make to their Camunda Platform 8 Self-Managed cluster configuration to upgrade their Elasticsearch instance from 7 to 8.

Note that these configuration options can be defined by the user or through the Helm Charts, but that the Helm Charts do not yet support these recent changes. The `retentionPolicy` value defined by the Helm Charts currently configures the deprecated Elasticsearch Curator. It is unclear how the charts will evolve to support the ILM Policy configurations provided by Zeebe's Elasticsearch Exporter.

**Comment by korthout** [comment]
We will consider this issue only about the Zeebe-related data retention policy. For Zeebe the changes are quite clear, so we can start to document this. We'll inform the other teams once this is documented so they can add their steps as well.

**Comment by korthout** [comment]
Note that the configurations themselves are documented in the ES exporter's docs already.

**Comment by akeller** [comment]
Was this issue associated with a PR that was already opened and merged? Any work remaining here or does the tag need to be adjusted for 8.3?

**Comment by korthout** [comment]
Thanks for noting @akeller 

This was resolved with 
- https://github.com/camunda/camunda-platform-docs/pull/1900
