### ISSUE TITLE
Update import statements for Zeebe in code snippets

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#1927]
Is this the correct import statement? Or should it be `/camunda/`?

_Originally posted by @akeller in https://github.com/camunda/camunda-platform-docs/pull/1917#discussion_r1160726445_

**Comment by akeller** [comment]
@megglos, assigning this to you, but feel free to assign it to someone else on your team.

**Comment by koevskinikola** [comment]
Individual ZPA triage:

- The link is actually correct, i.e. doing a `go install github.com/camunda-cloud/zeebe/clients/go/pkg/zbc...@latest` succeeds. Executing `go install github.com/camunda/zeebe/clients/go/pkg/zbc...@latest` will fail with the following message:

```
go install: github.com/camunda/zeebe/clients/go/pkg/zbc...@latest: github.com/camunda/zeebe/clients/go@v1.3.14: parsing go.mod:
        module declares its path as: github.com/camunda-cloud/zeebe/clients/go
                but was required as: github.com/camunda/zeebe/clients/go
```
- Unfortunately, I don't have a good understanding of Go packages to determine if we need to correct the docs, the Go package, or leave things as they are.

**Comment by remcowesterhoud** [comment]
ZPA Triage:
- We should update this
- The new import should be `github.com/camunda/zeebe/clients/go/v8/pkg/zbc`
- Small effort, with the current example users are importing the 1.3 version instead of our latest.
- Marking as `upcoming` as it's a very small fix

**Comment by megglos** [comment]
Closing due to the fact that [these statements got updated](https://docs.camunda.io/docs/next/apis-tools/go-client/) when the `zeebe` repository was renamed to `camunda`.
