### ISSUE TITLE
Inconsistent naming in release artifacts and docs

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda-docs#1967]
In a couple of places in the docs, we refer to zeebe artifacts as follows
```
tar -xzf zeebe-distribution-X.Y.Z.tar.gz -C zeebe/
```
@McAlm reported that this is confusing because the [release artifacts](https://github.com/camunda/camunda-platform/releases) is named `camunda-zeebe-XYZ`. I'm not sure if there was a reason not to use the names from the release. But please check it and make it consistent across the docs.

- https://github.com/camunda/camunda-platform-docs/blob/main/docs/self-managed/platform-deployment/manual.md#run-zeebe
- https://github.com/camunda/camunda-platform-docs/blob/main/docs/self-managed/backup-restore/zeebe-backup-and-restore.md#restore

**Comment by akeller** [comment]
@christinaausley is this something you could help triage? How many instances or how inconsistent is it? 

Scope: 8.0, 8.1, 8.2, `next` (all supported/maintained versions)
