### ISSUE TITLE
Remove "New Web Modeler" page

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2050]
The "New Web Modeler" (https://docs.camunda.io/docs/next/components/modeler/web-modeler/new-web-modeler/) has been introduced to inform previous Cloud Modeler users about the new Modeler and the migration happened. This page is now outdated and not needed anymore, hence we can remove it to reduce number of pages and information overload.

**Comment by akeller** [comment]
@christian-konrad, should we expect you to handle this in a PR? Let me know if you need any assistance from DevEx.

Two additional things to consider:

* Redirect to another page (Launch Modeler, perhaps)
* Remove images, unless they are used elsewhere

Would this be in scope for all supported versions? 8.0+?

**Comment by christian-konrad** [comment]
@akeller yes, I will file a PR for this! Thank you

> Would this be in scope for all supported versions? 8.0+?

It could, but not sure if it's worth the effort, I think we could limit it to 8.2 and next only.
