### ISSUE TITLE
Add "Publish via link" option to the "Run or publish your process" page

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2051]
Follow-up to https://github.com/camunda/camunda-platform-docs/issues/1990, after we added this page and implemented https://github.com/camunda/product-hub/issues/898

**Comment by volodymyr-melnykc** [comment]
The documentation was updated with the information on publishing via a public form: https://docs.camunda.io/docs/next/components/modeler/web-modeler/run-or-publish-your-process/#publish-via-a-public-form. Closing this issue.
