### ISSUE TITLE
Remove shadow from images

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2059]
I propose to remove the box shadow from images.

It just adds additional noise, and makes adding inline images impossible, since it looks odd.

A border/outline is sufficient to enclose the image.

Before:

<img width="1343" alt="Bildschirmfoto 2023-05-03 um 13 25 51" src="https://user-images.githubusercontent.com/56470362/235903163-edaf8427-ea56-4856-8982-3e6992098445.png">

After:

<img width="1316" alt="Bildschirmfoto 2023-05-03 um 13 26 15" src="https://user-images.githubusercontent.com/56470362/235903251-fefea594-8c51-43ec-9614-ee74c5c2bbc9.png">

**Comment by akeller** [comment]
https://camunda.slack.com/archives/C026U8GBNSW/p1728635884849279 thanks @mesellings!
