### ISSUE TITLE
Document support for converging inclusive gateway

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#2113]
The diverging inclusive gateway is added to Zeebe in https://github.com/camunda/zeebe/issues/10031 as an external contribution. Of course, all the Camunda Platform 8 need to be aligned and support the feature.

We need to document how users can use the converging Inclusive Gateway and how it behaves (in detail). We should also describe common pitfalls and special behaviors, for example, like the [Camunda 7 docs](https://docs.camunda.org/manual/7.21/reference/bpmn20/gateways/inclusive-gateway/#camunda-specific-behavior).

The following documentation section needs to be updated: https://docs.camunda.io/docs/next/components/modeler/bpmn/inclusive-gateways/

Link to product hub:
* https://github.com/camunda/product-hub/issues/364

**Comment by abbasadel** [comment]
Removing the target 8.3 label since we will revert it away from 8.3 release

**Comment by koevskinikola** [comment]
Setting the priority to `Not prioritized` as the converging inclusive gateway is not implemented yet, and it's not clear when ZPA will work on it.
