### ISSUE TITLE
Console screenshots have different org or usernames

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2132]
Most orgs in Console screenshots are ACME inc, but some are My Org like below:

[My Org](https://docs.camunda.io/docs/components/console/manage-organization/usage-history/):
![image](https://github.com/camunda/camunda-platform-docs/assets/1051363/5a9f1f69-020f-4778-8fa0-ce3b3e93492c)

Sometimes the user is Max Mustermann (schuppi+test@gmail.com) or Carl Camundatest's. 

This should be consistent and agreed on in our [Documentation guidelines](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#screenshot-automation).

**Comment by akeller** [comment]
@christinaausley, I know you worked on this previously. What was the agreed name/org we use for screenshot? I wasn't able to find it in the guidelines.

**Comment by christinaausley** [comment]
Closing in favor of [this issue](https://github.com/camunda/camunda-docs/issues/2815).
