### ISSUE TITLE
publish-stage & publish-prod fail often

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2182]
Example - https://github.com/camunda/camunda-platform-docs/actions/runs/5190102146

<img width="882" alt="image" src="https://github.com/camunda/camunda-platform-docs/assets/1051363/041ffea9-2682-4302-9d91-f58fc26e03d9">

publish-stage occasionally fails due to a timeout, but subsequent runs succeed with no issues. 

I'm labeling this a bug, but it doesn't seem to have the urgency/criticality of a bug, but something we should keep an eye on.

**Comment by akeller** [comment]
Hello darkness my old friend. This seems to have failed again - https://github.com/camunda/camunda-docs/actions/runs/6654215143/job/18081798816

**Comment by akeller** [comment]
This still appears to be occurring, but no one seems to be particularly bothered by it - https://github.com/camunda/camunda-docs/actions/workflows/publish-stage.yaml?query=is%3Afailure

**Comment by akeller** [comment]
This is back and happening more regularly in the last 24 hours.

**Comment by akeller** [comment]
Fun, now publish-prod is acting up. Rerunning https://github.com/camunda/camunda-docs/actions/runs/9762920404/job/26948549039

**Comment by akeller** [comment]
Raised to IT - https://camunda.slack.com/archives/CLRHYRTNC/p1719944491472149

**Comment by akeller** [comment]
I looked at increasing the `maxRetries` but I'm not convinced that will do anything based on https://github.com/haythem/public-ip/issues/23

I saw one alternative in the Marketplace, but it still appears to use ipify, which may actually be the [source](https://github.com/haythem/public-ip/issues/23#issuecomment-1396988869) of the issue.

IT closed my ticket saying they don't really do anything with Actions, but I don't know if we can use a different IP service. Marco will follow up with Tim directly. Moving this to Blocked.

**Comment by pepopowitz** [comment]
I also see in that linked haythem/public-ip issue some recommendations from people to access the URL `http://checkip.amazonaws.com/` in a manual step, to get the IP. Not that anyone here has suggested it yet, but I want to mention that I don't see that option as being any more safe or reliable than the current situation. In either case, we're relying on a website written and hosted by someone we don't know, and I don't know what it would take for one source to be considered far more reliable/trustworthy than the other.

**Comment by akeller** [comment]
I haven't noticed this failing recently, have you?

**Comment by pepopowitz** [comment]
I haven't.
