### ISSUE TITLE
Update the human task orchestration getting started guide

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2212]
The guide at https://docs.camunda.io/docs/guides/orchestrate-human-tasks/ is pretty outdated. We will update it so it reflects current features and helps users to understand the benefits of task routing, form design, approval flows, and start forms.

Next, we should also update the linked getting started video (TODO: separate issue).

**Comment by marcosgvieira** [comment]
@christian-konrad are you working on that, can you please update the ticket to the right column (Ready, Done, In Review) and provide an update in the comment so is easier to track what is going on with this? Thanks!
