### ISSUE TITLE
Add Beta Terms how to 

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2282]
https://confluence.camunda.com/display/HAN/Launching+the+Beta+Terms+Agreement+as+a+User

Open questions:

```
I have a few questions, but should be able to get a draft going this week.

Is this only for SaaS customers?

Is there a link to the Beta terms outside of the Console view?

What features or functionality are covered by Beta terms? (This is a short description to introduce the page.)

When does this need to be live? 

Eric are you the best person to review the PR?
```

**Comment by akeller** [comment]
@christinaausley, we got some answers on the Confluence page. You can move forward with creating the PR, but please apply a `hold` label and do not merge.

**Comment by christinaausley** [comment]
Currently working on a PR, and will have this finished by the end of the day for review next week.

**Comment by christinaausley** [comment]
Moving to `Backlog` until the final iteration is completed.
