### ISSUE TITLE
Document breaking change of non-root default user

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-docs#2340]
## Description

Starting with 8.3, the default user for Zeebe will be "zeebe", not root. This is a breaking change for existing deployments as previous data may have been written using different permissions. This means on update, it's possible data will not be read-able or write-able by 8.3.

The solution is to either:

1. Keep running as the root user, explicitly
2. Use an init container to rewrite permissions before starting Zeebe

```[tasklist]
### Tasks
- [x] Add and announcement of the breaking change to [Announcements](https://docs.camunda.io/docs/next/reference/announcements/) + information on why (security hardening + OWASP docker recommendations)
- [x] Add a section on the breaking change [to the update guide](https://docs.camunda.io/docs/next/guides/update-guide/820-to-830/) explaining the reason
```

**Comment by cmur2** [comment]
@megglos @npepinpe since https://github.com/camunda/camunda-docs/pull/2408 is merged and all sub-tasks of this ticket are done, do you think it can be closed?

**Comment by npepinpe** [comment]
Yes of course, let's do that :+1:
