### ISSUE TITLE
Replace Osano integration with OneTrust integration

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#2382]
The Web Marketing team is migrating from Osano to OneTrust, so we need to replace the code in https://github.com/camunda/camunda-platform-docs/blob/main/src/theme/Footer/index.js. 

## Notes from the Web Marketing Team

* We need to have this done by the end of September. We will then finish our contract with Osano and it's mandatory that we have our new cookie consent solution in place.
* The code should be testable outside of production. If there is Staging/Dev environment for docs.camunda.io we could test it there.

Related Epic - https://github.com/camunda/product-hub/issues/1546

**Comment by antantunes** [comment]
Urgency/timing -- is there a deadling for this? If so, how hard is the deadline?

- We need to have this done by the end of September. We will then finish our contract with Osano and it's mandatory that we have our new cookie consent solution in place.


What does the new code look like?

- It's a script just like Osano.


Is the code testable outside of production?

- If there is Staging/Dev environment for docs.camunda.io we could test it there.



Is anything changing in regards to MixPanel? The Osano code is tightly coupled with the MixPanel integration.

- I believe you referring to the code that checks if a user has accepted the Analytics before and then fires Mixpanel if consent has been given, is that right?
- If yes we will start by developing a solution with one of C8 applications and then share it with all other aplications/websites that need this feature.

**Comment by pepopowitz** [comment]
> > Is anything changing in regards to MixPanel? The Osano code is tightly coupled with the MixPanel integration.
>
> I believe you referring to the code that checks if a user has accepted the Analytics before and then fires Mixpanel if consent has been given, is that right?
> If yes we will start by developing a solution with one of C8 applications and then share it with all other aplications/websites that need this feature.

That is the code I'm referring to.

Does this mean we should disable the Mixpanel logic when we change from Osano to OneTrust, until you've developed a solution for other applications and bring it back here? Or will you have done that by the time we switch from Osano to OneTrust, and you will provide us with new Mixpanel logic then?

**Comment by antantunes** [comment]
The will have the new logic and test in staging with applications before we move to OneTrust in the production environment

**Comment by akeller** [comment]
Based on the update [here](https://github.com/camunda/product-hub/issues/1546#issuecomment-1843527204), I'm closing this issue. No action required for docs.
