### ISSUE TITLE
Review and move Camunda Platform 7 content in Best Practices to isolated section

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2393]
We have a dedicated area for Camunda Platform 7 content in the Best Practices section. However, we may have content for Camunda Platform 7 in the Camunda Platform 8 docs.

This area should be reviewed, and Camunda Platform 7 documentation should be moved to the isolated section, not embedded.

**Comment by christinaausley** [comment]
I can get started on this and https://github.com/camunda/camunda-docs/issues/2392 next week 🚀
