### ISSUE TITLE
Reference to Databases in process versioning - probably a copy past from Camunda 7 docs

### ISSUE THREAD

**Issue by jothikiruthika** [camunda/camunda-docs#2403]
In the Understanding versioning[​](https://docs.camunda.io/#understanding-versioning) section, the below phrase is not relevant to C8 - 
"when looking directly at Camunda database tables you can see different versions in the process definition table and the running process instances which are linked to these versions"

**Comment by berndruecker** [comment]
Good catch. I think we can delete this sentence to fit Camunda 8 better: https://github.com/camunda/camunda-docs/compare/main...berndruecker-patch-2?quick_pull=1
