### ISSUE TITLE
Clarify relationship between API Orchestration and Connectors

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2445]
Make it clearer that API orchestration is one use case within the Connectors component between the Guides.

https://camunda.slack.com/archives/C02JLRNQQ05/p1692126405979069?thread_ts=1684177781.748689&cid=C02JLRNQQ05

**Comment by christinaausley** [comment]
Quite timely with the docs review @jwulf and I are doing in Guides. Can we help here?

**Comment by akeller** [comment]
We have two existing Connectors guides, with the [API Orchestration guide](https://docs.camunda.io/docs/guides/orchestrate-api-endpoints/) as part of the **Getting started** experience. The [API Orchestration guide](https://docs.camunda.io/docs/guides/orchestrate-api-endpoints/) represents one of the three original use cases for launch Camunda Platform 8 and uses the REST connector, a protocol connector. 

The [other guide](https://docs.camunda.io/docs/guides/configuring-out-of-the-box-connectors/) demonstrates one of the many existing OOTB Connectors. 

With Connectors you can do many different things, including API orchestration, but not only API orchestration. We don't do a great job explaining that our API Orchestration Guide is just one way to work with Connectors. 

I could see both guides' beginning and end (intros & next steps) rewritten to clarify the relationship between API Orchestration and Connectors.

If this makes sense to either of you enough to start a draft PR, please remove me as an assignee and move forward. If you need more information, I'll start a draft PR later this week, and you can review and iterate from there.

**Comment by christinaausley** [comment]
We'll keep this separate from our existing work, but I'm happy to pop this into my Ready column to pick up. Does that work for you, or is this urgent?

**Comment by akeller** [comment]
This should be done before CamundaCon (if possible) since we'll have lots of eyes on the Connectors space.

If you move it into your Ready column, does that mean you'll draft the PR? Or do you need more info to get started?

**Comment by christinaausley** [comment]
Yeah, I can get this done before CamundaCon. If you have any additional details let me know, but otherwise I'll plan to have a look and draft a PR next week.
