### ISSUE TITLE
Recommendation chart in NodeJS is missing

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2446]
https://docs.camunda.io/docs/components/best-practices/development/writing-good-workers/#nodejs-client

At the end of each programming language-specific section, there should be a recommendation chart, but the values are missing for NodeJS.

```
This makes the recommendation very straight-forward:

||Reactive code|
| Parallelism | Event loop provided by Node.JS |
| **Use when** | Always |
```

This should be removed completely or filled in.

**Comment by akeller** [comment]
☝️ FYI @jwulf, something you could follow up with @berndruecker on.

**Comment by berndruecker** [comment]
I think just the formatting was broken, fixed: https://github.com/camunda/camunda-docs/pull/2683
