### ISSUE TITLE
Update navigation pattern in all Modeler guides and docs pages

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2491]
All Modeler guides and docs pages that explain how to navigate to Web Modeler refer to the old way of navigation, which was by a tab in Console. 

<img width="921" alt="Bildschirmfoto 2023-08-24 um 09 34 52" src="https://github.com/camunda/camunda-platform-docs/assets/56470362/04c06542-2aed-424f-b833-21c9d17de187">

However, this does not work anymore and may confuse readers. Instead, we should update the pages and mention the new global navigation bar.

Some affected pages:
* https://docs.camunda.io/docs/next/guides/model-your-first-process/
* https://docs.camunda.io/docs/next/guides/orchestrate-api-endpoints/
* https://docs.camunda.io/docs/next/guides/orchestrate-microservices/
* https://docs.camunda.io/docs/next/components/modeler/web-modeler/launch-cloud-modeler/

**Comment by akeller** [comment]
@christian-konrad do you need DevEx to assist with this? If so, please check with @christinaausley. Currently, it's not on anyone's board so I don't want it to get missed by accident.

**Comment by christinaausley** [comment]
Note that all of the guides have been updated in https://github.com/camunda/camunda-docs/pull/2596 👍
