### ISSUE TITLE
Review system-configuration-platform-8 in Optimize docs

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2496]
There are 3 similarly named system-configuration-* docs for Optimize.

This page is quite lean - https://docs.camunda.io/optimize/self-managed/optimize-deployment/configuration/system-configuration-platform-8/

Should `system-configuration-platform-8.md` be consolidated into `system-configuration.md`? Or is there additional context we can add to this page if we keep it? 

Marking this as a bug since it seems out of place and needs a little love.

**Comment by akeller** [comment]
@christinaausley, this is out of scope for the changes @toco-cam was planning, correct? His changes are isolated to the UI side based on the target persona - business users, but can you confirm?

**Comment by christinaausley** [comment]
Confirmed with @toco-cam this is a separate change, and I'm happy to pop this in my backlog.

**Comment by akeller** [comment]
I think this is irrelevant at this point, so I'm closing it out. With the upcoming docs split, I don't think consolidating these pages makes sense.
