### ISSUE TITLE
Output mapping description is outdated

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2513]
In https://docs.camunda.io/docs/components/concepts/variables/#output-mappings, the description for output mapping says

> Output mappings can be used to customize how job/message variables are merged into the process instance. They can be defined on service tasks, receive tasks, message catch events, and subprocesses.

However, they can also be used for script and user tasks, and they are not just about job and message variables, but all types of result variables.

**Comment by akeller** [comment]
@christinaausley this looks like a quick fix. When you review the Concepts section, there are likely other areas or issues similar to this that are simply outdated as the product has grown and changed.

**Comment by christinaausley** [comment]
I'll plan to review that section next. In the meantime, I'll assign to myself! 👍
