### ISSUE TITLE
Link to Cluster Settings in the Resource Authorization Chapter

### ISSUE THREAD

**Issue by mschoe** [camunda/camunda-docs#2551]
As an outcome of the [Resource Authorization QA](https://github.com/camunda/product-hub/issues/1397) I suggest the following improvement for the respective docs `components/console/manage-organization/manage-users/`.

Related Epic: https://github.com/camunda/product-hub/issues/1012

# Improvement
Add a reference to `components/console/manage-clusters/settings/ `on the page `components/console/manage-organization/manage-users/ `. This will help the user to understand where to enable `Resource Authorizations`.

**Comment by akeller** [comment]
Covered by https://github.com/camunda/camunda-platform-docs/pull/2366?

**Comment by akeller** [comment]
@mschoe can you add the Engineering DRI when you open a QA issue like this in the future? This was missed. 

@Ben-Sheppard can you confirm this is taken care of? If not, please open a PR.
