### ISSUE TITLE
Document C8 multi-tenancy (in self-managed)

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#2561]
### Description

With https://github.com/camunda/product-hub/issues/197, Camunda Platform 8 (self-managed) will support multi-tenancy. The feature needs to be documented to help users understand its purpose and how to configure and use it.

The following tasks need to be performed:

The following tasks should document multi-tenancy for the whole C8 platform
```[tasklist]
### C8 platform
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2562
- [ ] https://github.com/camunda/camunda-platform-docs/issues/2563
```

```[tasklist]
### Zeebe
- [ ] https://github.com/camunda/camunda-docs/issues/2697
- [ ] https://github.com/camunda/camunda-docs/issues/2686
- [ ] https://github.com/camunda/camunda-docs/issues/2700
- [x] Document that the Zeebe Go client doesn't support multi-tenancy
```

```[tasklist]
### Other components
- [x] https://jira.camunda.com/browse/OPT-7250
- [ ] https://github.com/camunda/tasklist/issues/3431
```

**Comment by korthout** [comment]
The added config option `zeebe.gateway.multiTenancy.enabled` should be documented as well: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/configuration/gateway-config/

**Comment by PHWaechtler** [comment]
[Here ](https://jira.camunda.com/browse/OPT-7250)is the Optimize doc ticket, I am adding to the list of items to document as I am progressing with implementation so more items may be added.

**Comment by akeller** [comment]
I am following up on docs with @abbasadel during code freeze.

**Comment by remcowesterhoud** [comment]
As users must assign a tenant to their clients when enabling MT, we must also make sure to document in the upgrade guide that users assign the `<default>` tenant to their current client. Otherwise, they lose access to their resources.

**Comment by remcowesterhoud** [comment]
@koevskinikola since you're working on this, could you make sure you add to the upgrade guide for SM that:

If they have the experimental consistency checks enabled, the upgrade will take a lot longer. For 1 million instances it took about an hour for Zeebe to finish the migration enough to start processing again. Without this took < 1 minute. We recommend:
1. If the downtime is fine leave the consistency checks on. It's an extra layer of security.
2. If the downtime is unacceptable, to disable the consistency checks before upgrading.

It's a tradeoff between downtime and risk of inconsistency.

**Comment by koevskinikola** [comment]
Closing as all sub-tasks are completed.

**Comment by anumolurahul** [comment]
is multi tenancy configurable without identity?

The documentation is a bit confusing

https://docs.camunda.io/docs/self-managed/operational-guides/configure-multi-tenancy/ says
`Multi-tenancy is currently only available for Camunda 8 Self-Managed with authentication enabled [through Identity]`

where as https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/#implementing-a-tenant-providing-interceptor says 

`However, if you decide to use Zeebe as a standalone product with multi-tenancy enabled, you need to provide your own component for managing tenants. You can integrate your tenant-managing component with Zeebe by implementing a tenant-providing interceptor which provides the Zeebe Gateway with a list of authorized tenant IDs.`

**Comment by akeller** [comment]
@anumolurahul, if you plan to use Zeebe standalone, you can have multi-tenancy, but you need to create/implement an interceptor. Identity is not present in the standalone scenario.

If you have more questions, I would recommend using the [forum](https://forum.camunda.io/) for better visibility and faster responses.

**Comment by anumolurahul** [comment]
sure thank you, I've a follow up question on tenant level metrics. posted to the forum [here](https://forum.camunda.io/t/tenant-level-metrics-for-self-managed-standalone-zeebe-installation/53925)
