### ISSUE TITLE
Provide documentation on setting up multi-tenancy for self-managed

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#2563]
### Description

We should provide a guide on how users can configure the C8 platform with multi-tenancy (MT).

```[tasklist]
### AC
- [x] Link to all the dedicated C8 application doc sections for MT configuration
- [ ] ~Document how to setup MT on C8 SM with Helm.~
- [ ] ~Document how to setup MT on C8 SM with Docker.~
- [ ] ~Document how to setup MT on C8 SM manually.~
```

**Comment by koevskinikola** [comment]
The Helm/Docker/manual installation docs don't document how to enable specific features. 

Enabling features is documented in the "configuration" sections of each C8 component, and these sections are linked in the conceptual page of the feature (ex. multi-tenancy). Users should adjust the configurations of their installation according to the installation type.

**Comment by koevskinikola** [comment]
Currently, still missing:
* Tasklist - added with #2730 
* Operate

**Comment by sdorokhova** [comment]
Operate PR is in review: https://github.com/camunda/camunda-docs/pull/2762

**Comment by koevskinikola** [comment]
Closing as all sub-tasks are completed.
