### ISSUE TITLE
Bug: API-tools cards have different sizes

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#2569]
### Description

The cards on the api-tools page have different sizes, the orientation looks strange.

### How to reproduce

Visit https://docs.camunda.io/docs/apis-tools/working-with-apis-tools/.

See 
![Bildschirmfoto 2023-09-10 um 21 31 38](https://github.com/camunda/camunda-platform-docs/assets/42800119/46321aca-dd5d-4aaf-ad2c-49fa85582e99)

### Suggestion

Ensure same width of all cards.
(Maybe consult with a Designer what to do here.)

**Comment by christinaausley** [comment]
Paired work with Steve on this today and tomorrow 👍
