### ISSUE TITLE
Introduce Guides section for Self-Managed

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2615]
Some Guides are only relevant for Self-Managed users, but currently exist together with the SaaS Guides. This can be confusing or misleading about what you can do in SaaS vs. Self-Managed.

Currently, these docs live under "Next steps".

* Set up your first development project (currently very SM-oriented)
* Message correlation
* ...

Additional Guides may already exist in component-specific docs in Self-Managed. This should be audited and moved into a single Guides area within Self-Managed.

This can happen in parallel with https://github.com/camunda/camunda-platform-docs/issues/2614. 

This is related to feedback and collaboration with https://github.com/camunda/developer-experience/issues/96.

**Comment by christinaausley** [comment]
Do we want to close this in favor of work with https://github.com/camunda/camunda-docs/pull/3988?

**Comment by akeller** [comment]
What's old is new again 🌟
