### ISSUE TITLE
Fix inline image in new HTO guide

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2645]
There's an image displaced: 
<img width="1434" alt="image" src="https://github.com/camunda/camunda-platform-docs/assets/56470362/11adeda4-94b2-451c-a06b-80d6acb7e5ea">

It appears inline, but it shouldn't. (You will not notice unless you zoom or resize the window)

**Comment by akeller** [comment]
During the PR review, I saw two images with this issue. My recommendation was to drop it to a new line - https://github.com/camunda/camunda-platform-docs/pull/2465#discussion_r1318824081. Step 2 also has a similar experience - 
<img width="1264" alt="image" src="https://github.com/camunda/camunda-platform-docs/assets/1051363/fb6599a0-902a-4fac-bc43-b9f97d6acebf">

**Comment by douglasbouttell-camunda** [comment]
Closing this as this seems to be fixed already
