### ISSUE TITLE
Define formatting and copywriting guidelines for product UI

### ISSUE THREAD

**Issue by karl-heinsen** [camunda/camunda-docs#2661]
### Description

refers to https://github.com/camunda/camunda-platform-docs/pull/2618#issuecomment-1730041328 & https://github.com/camunda/camunda-platform-docs/pull/2618#issuecomment-1734050906

### Checklist

- [x] **Components or Applications:** Define how we refer to other Camunda apps (currently UI refers to them as apps, but docs uses components)
- [x] **Formatting for components, features and entities:** Clusters, connectors, process/decision instances, connectors, clusters, forms, IP allowlist, process/decision instances etc. (Clusters and IP Whitelist is currently uppercase in Console - assuming these should change to lowercase to be inline with docs)
- [x] **Formatting for Camunda platforms:** Marketplace, blog, docs, etc. 
- [x] **Referring to documentation:** Define how we refer to documentation within our products. Example: Learn more vs To {address issue} visit {doc link}
- [x] Add product UI guidelines to internal/external style guide assets

**Comment by christinaausley** [comment]
Hi @karl-heinsen! Thanks for launching this issue. Going to pop some time on your calendar so we can discuss next week.

**Comment by karl-heinsen** [comment]
@christinaausley happy to be addressing this issue :) Product design's POV is to ensure that it is as close to docs formatting and guidelines as possible. I have created [this issue](https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1283) in Console repo to track eventual text changes.

**Comment by akeller** [comment]
Re: application vs. components, I wasn't sure if this was related to Keycloak or something we have control over - https://github.com/camunda/camunda-docs/issues/2630. Are these topics related?

**Comment by christinaausley** [comment]
@karl-heinsen and I met yesterday to discuss here -- sharing across Slack for additional feedback, though my personal preference is Components and connectors rather than applications and Connectors.

As far as how we refer to documentation within our products, To {address issue} visit {doc link} makes the most sense to me so the user has more direction as to what they are about to click on and what exactly they will find. I'll ship this notification out with my WCoE release this month.

**Comment by akeller** [comment]
@christinaausley should this be on the Developer Experience board?

One outcome I would like to see from this effort is adopting the [Writing Style Guide](https://camunda.com/brand/writing-style-guide/) in the product UI or clear internal documentation stating why this can't happen. This will make consistency and reviews easier across all spaces, no matter what function or team is working on it.

**Comment by christinaausley** [comment]
Agreed -- we should add to the DX board. I think I need to spend dedicated time ensuring product UI is alongside my usual documentation review.

**Comment by christinaausley** [comment]
Tracking ongoing progress:

- [x] Sync with Console team for corrections. (11/3)
- [ ] Make UI adjustments. (11/3)
- [ ] Document regular review process with team. (11/3)
- [ ] Sync with Modeler team. (11/10)
- [ ] Make UI adjustments. (11/10)
- [ ] Document regular review process with team. (11/10)
- [ ] Sync with Connectors team. (11/17)
- [ ] Make UI adjustments. (11/17)
- [ ] Document regular review process with team. (11/17)
- [ ] Sync with Operate/Tasklist team. (11/24)
- [ ] Make UI adjustments. (11/24)
- [ ] Document regular review process with team. (11/24)
- [ ] Sync with Optimize team. (12/8)
- [ ] Make UI adjustments. (12/8)
- [ ] Document regular review process with team. (12/8)
- [ ] Sync with Identity team. (12/15)
- [ ] Make UI adjustments. (12/15)
- [ ] Document regular review process with team. (12/15)

**Comment by christinaausley** [comment]
See https://docs.google.com/document/d/12H3jTnUe2C2w60U_9YRCNwQvWMnbk9IEmRfNbvULrKc/edit?usp=sharing for my ongoing (albeit ugly) documentation of the review processes, which will move into https://confluence.camunda.com/pages/viewpage.action?pageId=105513381 upon completion.

**Comment by karl-heinsen** [comment]
@akeller @christinaausley We have changed "applications" to "components" on the cluster overview page in Console, and the tooltip for the product switcher will soon change to "Camunda components". 

Are there documentation changes needed to reflect this update?

<img width="382" alt="image" src="https://github.com/camunda/camunda-docs/assets/98960247/ca59679e-c036-49d0-941b-13a4f496707e">

<img width="368" alt="image" src="https://github.com/camunda/camunda-docs/assets/98960247/75d165db-f490-4b56-a25b-4140e5b43e04">

**Comment by christinaausley** [comment]
> @akeller @christinaausley We have changed "applications" to "components" on the cluster overview page in Console, and the tooltip for the product switcher will soon change to "Camunda components".
> 
> Are there documentation changes needed to reflect this update?

Yes -- there are. I'll add this as an item in my Tasklist.

**Comment by karl-heinsen** [comment]
@christinaausley alright, thanks!

**Comment by christinaausley** [comment]
> > @akeller @christinaausley We have changed "applications" to "components" on the cluster overview page in Console, and the tooltip for the product switcher will soon change to "Camunda components".
> > Are there documentation changes needed to reflect this update?
> 
> @karl-heinsen Yes -- there are. I'll add this as an item in my Tasklist.

Resolved in https://github.com/camunda/camunda-docs/pull/3113 👍

**Comment by christinaausley** [comment]
To revisit Identity UI pending hiring of frontend engineer in a few weeks -- created a separate issue and closing this one as complete! https://github.com/camunda/developer-experience/issues/220
