### ISSUE TITLE
Small diagram change to make it clear

### ISSUE THREAD

**Issue by 1nb0und** [camunda/camunda-docs#2674]
The item `B` is missing or is hidden in the back and may make users confusing. It makes sense once you read the whole doc. Maybe we can recreate the screenshot of this process again with B at the front

[Page](https://docs.camunda.io/docs/components/concepts/process-instance-modification/)

![image](https://github.com/camunda/camunda-docs/assets/133918079/41d1312d-148e-4365-a0d8-069b47b43a75)

**Comment by akeller** [comment]
@christinaausley this is an image in the Concepts section. Could you look into updating this with #2742?

**Comment by christinaausley** [comment]
Hi @1nb0und -- looks like this is in Operate.

I'm going to include this in my Operate docs review this week/next week given the chaos that has been the Concepts review, lol.

This may be as simple as replacing the screenshot, but per the comment by @akeller, may need to advise the team on this. In Modeler, we don't have this overlap.
