### ISSUE TITLE
Link from Getting Started Guides to corresponding process template

### ISSUE THREAD

**Issue by shaarmann** [camunda/camunda-docs#2759]
The documentation includes three getting started guides:

- Getting started with human task orchestration
- Getting started with API orchestration
- Getting started with microservice orchestration

For each guide, the Webmodeler template picker includes a process template. For each template, a direct link exists that opens the model in a new tutorial project inside the Webmodeler. 

We should add these links to the getting started guides (see [Getting started with human task orchestration](https://docs.camunda.io/docs/guides/orchestrate-human-tasks/#wrap-up) for an example):
![image](https://github.com/camunda/camunda-docs/assets/5269168/68799d2b-e665-4d7c-bca7-e2e3778bd69e)

**Goals:**
- improve engagement with process templates
- increase sign-ups

**Comment by shaarmann** [comment]
FYI: @HanselIdes, @christinaausley

**Comment by christinaausley** [comment]
@shaarmann This is cool, I would just link to [build the process yourself](model your first process), so users understand we still have comprehensive documentation for building models if they want to.
