### ISSUE TITLE
Make unsupported multi-tenancy features more visible

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#2781]
### Description

Add unsupported functionality in the scope of multi-tenancy in the dedicated conceptual page for multi-tenancy.

```[tasklist]
### AC
- [x] Document unsupported (custom tenant) signal broadcasting for `8.3`
- [x] Document unsupported (custom tenant) resource deletion for `8.3`
- [x] Note that the above features are supported for the `<default>` tenant.
- [x] Document that Go client doesn't support multi-tenancy for `8.3`
- [x] Document that CLI client doesn't support multi-tenancy for `8.3`
```

**Comment by akeller** [comment]
@koevskinikola would it help to have these on a project board? ZPA board?

**Comment by koevskinikola** [comment]
Hey @akeller, yes it would. The ZPA project board was full and I wasn't able to place the issue there. We cleared up some issues last week, so I can add it now.
