### ISSUE TITLE
Architecture diagram lacks Ingress for Optimize

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#2797]
This diagram from https://docs.camunda.io/docs/self-managed/platform-architecture/overview/ is lacking the connection between the Ingress and Optimize:
![image](https://github.com/camunda/camunda-docs/assets/40038/06fd70e2-c382-4e4a-b407-f984b9028483)

**Comment by akeller** [comment]
@aabouzaid can you update this diagram? I believe you were the original creator.

**Comment by akeller** [comment]
FYI @RomanJRW

**Comment by aabouzaid** [comment]
Fixed by: https://github.com/camunda/camunda-docs/commit/4c0a703a032a827e93d2ea7d91f913581f68fbe9
