### ISSUE TITLE
I can read how to use BPMN compensation events

### ISSUE THREAD

**Issue by saig0** [camunda/camunda-docs#2802]
## Description

With Camunda 8.5, we will add support for BPMN compensation events. We need to write documentation on how to use compensation events. 

The documentation will be placed in the BPMN section: `Components > Modeler > BPMN > Events`.

The documentation should cover the following points:
- How to trigger compensation
- Trigger compensation for the scope vs. for a given activity
- Trigger compensation from an event subprocess
- How to compensate an activity with a compensation handler
- Under which conditions is a compensation handler invoked and how often
- How compensation works for subprocesses
- How compensation works with multi-instance
- No compensation for child process instances 
- When is a compensation handler interrupted
- Explain the compensation order (i.e. all compensation handlers at once) and how to enforce a specific order

**Comment by megglos** [comment]
@saig0 with alpha2 we will have a first functional increment supporting some elements, right? Are we planning to make that transparent in the docs so we can refer users to that?

**Comment by saig0** [comment]
@megglos no. We don't have the resources to write the docs until the alpha2 release.
