### ISSUE TITLE
Sizing example doesn't make sense

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#2805]
The last sentence of this paragraph doesn't seem to make sense:
https://github.com/camunda/camunda-docs/blob/af4deb9e85588c8a0d54039f95655d62051fb008/docs/components/best-practices/architecture/sizing-your-environment.md?plain=1#L164

With 500k PI/d and a conservative 30-day history retention policy would lead to at least 15M PI that would have to be stored in history.

Proposal: split up the sentence to make clear that they are unrelated. The 500kPI/d have probably been interpolated from the peak throughput in PI/s that this cluster could handle. However the history setup clearly only permits short bursts at that rate of throughput. So maybe it's better to specify maximum throughput in PI/s instead of PI/d to not give people a wrong idea. Alternatively, one could mention that more storage resources would be needed to sustain such a high throughput.

Bonus points for breaking the Markdown sources at 80 characters per line so issues can point more directly to a sentence ;-P

**Comment by akeller** [comment]
@berndruecker can you have a look at this feedback?

**Comment by berndruecker** [comment]
Make sense to me. Those figures are really unrelated and I think it caused confusion already in the past.

@falko: WDYT of https://github.com/camunda/camunda-docs/pull/2811
