### ISSUE TITLE
Document cluster tags on Console

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2860]
There are 4 different tags that can be set for a cluster, either on creation or assigned after.

* Dev
* Test
* Stage
* Prod

![image](https://github.com/camunda/camunda-docs/assets/1051363/1fb6ac26-fa7d-473a-ac3a-5b652eadb766)

We should add a page to the Console section that describes how to tag a cluster and what each cluster means.

Scope - 8.3 and `/next/`

FYI @felix-mueller

**Comment by felix-mueller** [comment]
Thank you @akeller !
