### ISSUE TITLE
Document Update Job Timeout feature

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda/camunda-docs#2862]
## Description

Zeebe implemented the Update Job Timeout feature. We should document the API, explain the use-cases and how to use the feature.

- [x] Document the gRPC API. Part of [this page](https://docs.camunda.io/docs/apis-tools/grpc/)
- [x] Document use-cases and how to use. Can be part of [this page](https://docs.camunda.io/docs/components/concepts/job-workers/)
    - Please make sure to mention that a Job Worker should not wait until the last second to extend a Job. Zeebe may need time to process the update and in between the Job could already time out. To be on the safe side a buffer should be applied.

**Comment by akeller** [comment]
Looks like this will not be ready for today's alpha. Changing the label to 8.4.
