### ISSUE TITLE
Variable `currentWeather` is not defined

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#2868]
https://github.com/camunda/camunda-docs/blob/47ea05e58450e7fc0552bdde2fd521d336a4d2bc/docs/components/connectors/protocol/rest.md?plain=1#L172

It's unclear how the variable `currentWeather` is defined. I assume that it means that variable name is defined by setting the `resultVariable` header to `currentWeather`. But then it is not explained very well that the `resultExpression` is not an alternative to setting  `resultVariable` but just reshapes it's contents. How can I get just the body of the REST response into the result variable i.e. without wrapping it into a context?

**Comment by akeller** [comment]
Raised to Connectors team - https://camunda.slack.com/archives/C02JLRNQQ05/p1699376814200539

**Comment by igpetrov** [comment]
Hi @falko, @akeller 

Thank you for bringing it to Connectors team attention.

Some time ago we removed screenshots from our several pages. The `currentWeather` was unfortunately referring the [https://github.com/camunda/camunda-docs/blob/441336576fd41bcbef4c2da79816ee9f4a5ff[…]onents/connectors/img/connectors-rest-http-response-mapping.png](https://github.com/camunda/camunda-docs/blob/441336576fd41bcbef4c2da79816ee9f4a5ff231/versioned_docs/version-8.2/components/connectors/img/connectors-rest-http-response-mapping.png) and without it, the page losses context.

We will fix it shortly.

Please let us know if there's any other concerns. Thank you.

**Comment by igpetrov** [comment]
Will be addressed here https://github.com/camunda/camunda-docs/pull/2916

**Comment by igpetrov** [comment]
Merged in https://github.com/camunda/camunda-docs/pull/2942/files
