### ISSUE TITLE
Support ES 8.9+ (8.9 as minimum version)

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2886]
- [x] [Update Supported environment page](https://github.com/camunda/camunda-docs/pull/3019)
- [x] Search & review remaining docs pages for 8.8+ 
  * Update or remove content
- [x] Review update guide to nudge users to ES 8.9+

**Comment by christinaausley** [comment]
@akeller We can discuss this in our 1:1, but happy to assist as you're headed offline after tomorrow 🥳

**Comment by christinaausley** [comment]
@MaxTru -- I'll be wrapping this up. I'm online all of next week, so anticipate completion then 👍

**Comment by akeller** [comment]
We have a specific page for updating from 7 to 8, but I haven't heard of any specific requirements about updating from 8.8 to 8.9 that would warrant a page. 

Looking at the ES docs, they have a page for [migrating to 8.9](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.9.html), but it's quite lean. I don't think it's worth linking to this page, but WDYT @christinaausley?

Once you 👍 https://github.com/camunda/camunda-docs/pull/3005 the update guide will be available you can add a one-liner about upgrading, and I think that would sufficiently tick the last box on the list.

**Comment by christinaausley** [comment]
> Looking at the ES docs, they have a page for [migrating to 8.9](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-8.9.html), but it's quite lean. I don't think it's worth linking to this page, but WDYT @christinaausley?

Agreed. This is far too lean to warrant a link. If users complain about REST, we can add a specific admonition for that.
