### ISSUE TITLE
Document new records and events

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda-docs#2917]
Zeebe is introducing a new record value type with:

- https://github.com/camunda/zeebe/issues/14996

Records of this value type can be exported by the ES and OS exporters through configuration:
- `index.userTask` (boolean flag)

This must be documented in the respective pages:
- https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/
- https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/opensearch-exporter/

**Comment by koevskinikola** [comment]
The PR is already approved, but on hold until the actual code is merged.

**Comment by tmetzke** [comment]
Actual code is merged, docs are merged 👍
