### ISSUE TITLE
CLI client quick reference is outdated

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#2954]
### Observation

https://docs.camunda.io/docs/apis-tools/cli-client/ is outdate. For example the recently added `delete` command is not present.

### Expectation

https://docs.camunda.io/docs/apis-tools/cli-client/ is up to date with latest commands for zbctl.

**Comment by akeller** [comment]
Do you mean in the screenshot? Or do you expect to see it in the guide as well?

**Comment by MaxTru** [comment]
I mean in the usage code-block. Compare with latest available commands:

```
Available Commands:
  activate    Activate a resource
  broadcast   Broadcast a signal
  cancel      Cancel resource
  complete    Complete a resource
  completion  Generate the autocompletion script for the specified shell
  create      Create resources
  delete      Delete resources
  deploy      Deploys new resources for each file provided
  evaluate    Evaluate resources
  fail        Fail a resource
  generate    Generate documentation
  help        Help about any command
  publish     Publish a message
  resolve     Resolve a resource
  set         Set a resource
  status      Checks the current status of the cluster
  throwError  Throw an error
  update      Update a resource
  version     Print the version of zbctl
```

**Comment by akeller** [comment]
I'm not sure where the [npm docs sit](https://www.npmjs.com/package/zbctl). @jwulf do you know? They are also outdated, including references to Camunda Cloud.
