### ISSUE TITLE
Document the proper use of variable filters

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#2986]
In the Tasklist API, every variable used must be JSON.stringified first (even strings must be wrapped in escaped quotes, e.g. `"\"value"\"`). This is not clear from the docs, and there is no useful error on the API that helps the user discover this behavior.

We need to document this in every single page where the variable filters (the queries, the variable object...) are documented.

**Comment by nathansandi** [comment]
Review on https://github.com/camunda/camunda-docs/pull/3045/files

**Comment by marcosgvieira** [comment]
@nathansandi let's try to explain a bit more on that and the reasonings behind the examples, reopening this one.

**Comment by nathansandi** [comment]
New PR for review: https://github.com/camunda/camunda-docs/pull/3135
