### ISSUE TITLE
Link multi-tenancy docs and tenant docs

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#2992]
It's unclear how to manage tenants and we should link between the [multi-tenancy docs](https://docs.camunda.io/docs/self-managed/concepts/multi-tenancy/) and the [tenant docs](https://docs.camunda.io/docs/self-managed/identity/user-guide/tenants/managing-tenants/).

_Thanks for raising this, @pierre-yves-monnet!_

**Comment by akeller** [comment]
@christinaausley can I assign this to you to further improve after I merge #2997?

**Comment by akeller** [comment]
With #2997 merged, this is truly `Ready` for you whenever @christinaausley 😄

**Comment by christinaausley** [comment]
I'll get started on this on Monday 👍

**Comment by christinaausley** [comment]
I've linked this documentation in #3103, but let me know if I need to open another issue altogether to review our managing tenants doc in full. Are users not sure how do do this based on the page content, or because they can't get to the page in the first place? My PR resolves the latter.

**Comment by akeller** [comment]
@christinaausley great question. Please open a separate issue for the tenants doc since there are a lot of moving pieces with the multi-tenancy feature.
