### ISSUE TITLE
Evaluate references of app switcher

### ISSUE THREAD

**Issue by christinaausley** [camunda/camunda-docs#3012]
Evaluate naming of app switcher -- both if this should be component switcher, or named a "X switcher" at all given its awkwardness. Adjust across docs/UI as appropriate. https://github.com/camunda/camunda-optimize/pull/9558#discussion_r1417866453

**Comment by akeller** [comment]
@christinaausley pay careful attention to https://github.com/camunda/product-hub/issues/1967

**Comment by christinaausley** [comment]
^ CC @melanie-butcher @karl-heinsen

**Comment by theburi** [comment]
I am not aware of the discussion around App Switcher. Its probably a organic naming

**Comment by christinaausley** [comment]
Given there are not currently any instances of this in the docs, and we haven't received strong feedback, I am going to leave this with https://github.com/camunda/product-hub/issues/1967. May re-open this issue as progress is made with the Product Hub issue, but believe this may be out of scope for docs currently. Will continue to monitor the Product Hub issue in the meantime.
