### ISSUE TITLE
Update Process Instance Migration concept for 8.4 release

### ISSUE THREAD

**Issue by abbasadel** [camunda/camunda-docs#3051]
Based on @korthout [comment](https://github.com/camunda/camunda-docs/pull/3000#issuecomment-1847526591)

These are the needed updates before `8.4` release

- [ ] We can remove the danger banner at the top as soon as we resolve: camunda/zeebe/issues/15129 
- [x] Near the top of the page is a `note` admonition that navigates readers to Operate's user guide for process instance migration. It's not yet available, but the link has to be adjusted when it does become available. You can track that documentation in: https://github.com/camunda/camunda-docs/issues/2848

Related #2900

**Comment by berkaycanbc** [comment]
@abbasadel the second requirement of this issue is already implemented in #2848 (see https://github.com/camunda/camunda-docs/pull/3022/files#diff-883666aa04ce4a7457601d1bb4ba38eb6d013459f61f01d0b7a2569173769e3bR31). I will only remove the danger banner. 👍

**Comment by akeller** [comment]
I mentioned this on the PR, but we should also consider adding an announcement for this feature to https://docs.camunda.io/docs/next/reference/announcements/
