### ISSUE TITLE
Set snapshot period in Zeebe config at 5m, not 15m

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3067]
<img width="1344" alt="image" src="https://github.com/camunda/camunda-docs/assets/1051363/f1845ef0-28f5-4c37-8438-a4929ec3cb14">

Based on a conversation on https://github.com/camunda/camunda-docs/pull/3052, this value should be 5m in both the docs and template. In this case, they both match, but are incorrect, per https://github.com/camunda/zeebe/issues/15625.

**Comment by akeller** [comment]
@npepinpe can you confirm before I create a docs PR?

**Comment by npepinpe** [comment]
Yes, 5m is the right value.
