### ISSUE TITLE
Fix inaccuracies introduced through experimentation

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3080]
1. The following guides assume the user begins in the Console and not Modeler. We should explain how to get to the Console, not to Modeler. Here are some examples:
"Click the checkerboard-like icon to open the global navigation and click Modeler to navigate to Web Modeler." `i'm already there`
"To create a BPMN diagram, navigate to Web Modeler via the square-shaped icon in the top left corner of the page. Click Modeler, and then click New project." `i'm already there`
"To create a cluster, navigate to Console, click the Clusters tab, and click Create new cluster." `how?`

- [ ] https://docs.camunda.io/docs/next/guides/getting-started/ 
- [ ] https://docs.camunda.io/docs/next/guides/model-your-first-process/ 
- [ ] https://docs.camunda.io/docs/next/guides/orchestrate-microservices/
- [ ] https://docs.camunda.io/docs/next/guides/setting-up-development-project/
- [ ] https://docs.camunda.io/docs/next/guides/create-cluster/
- [ ] https://docs.camunda.io/docs/next/guides/configuring-out-of-the-box-connectors/
- [ ] https://docs.camunda.io/docs/next/guides/utilizing-forms/
At this point I stopped tracking individual sections of the guide. Every guide should be checked

I think they can be holistically addressed by updating a few reusable sections
"Create a cluster"/ "Create your cluster"
"Getting started"
"Create a new file

2. The Help Center has a feedback option to report bugs and share feedback privately. It's monitored by Product Management, so they should not expect 1:1 support. For help, users should still go to the forum because it's monitored more closely. https://docs.camunda.io/contact/

**Comment by christinaausley** [comment]
I'm going to launch a PR today to default to launching in Modeler, and moving to Console. Keep me updated on any customer feedback in the case we need a hybrid or more app-agnostic approach moving forward.

**Comment by christinaausley** [comment]
> The Help Center has a feedback option to report bugs and share feedback privately. It's monitored by Product Management, so they should not expect 1:1 support. For help, users should still go to the forum because it's monitored more closely. https://docs.camunda.io/contact/

This seems somewhat related to https://github.com/camunda/developer-experience/issues/129 and https://github.com/camunda/camunda-docs/pull/2834. Are there instances in the docs which we do not route to the contact page where we should?

**Comment by akeller** [comment]
@christinaausley let's adjust the contact page slightly to include this support option available in the Help Center. In the second sentence, can you add the Help Center option?

> Feedback and support can be submitted or requested via JIRA for subscription or enterprise customers in the Support project. Otherwise, use the [Camunda community forum](https://forum.camunda.io/). For more information about Enterprise support and additional support resources, see [Enterprise Support](https://camunda.com/support/).

Something like "all users can find feedback and support options in the Help Center or Camunda community forum."
