### ISSUE TITLE
Rename first page of "Components" section

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3127]
We should rename the first page of the "Components" section. It is called "Overview Components", which is not proper English.
We should rename it to "Component Overview".

<img width="1485" alt="image" src="https://github.com/camunda/camunda-docs/assets/56470362/2f0a79ba-7b4a-4e6a-b9bc-5be16f47681f">

**Comment by christinaausley** [comment]
Nice catch! I'll take care of this 👍
