### ISSUE TITLE
Operate configuration parameters is env var format

### ISSUE THREAD

**Issue by sdorokhova** [camunda/camunda-docs#3165]
Currently we document [Operate parameters in Yaml format](https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/) (camel case with dots separation). But it looks like they are more often used as environmental variables. E.g. Tasklist [uses both formats to document their configuration](https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-configuration/). Optimize also [uses both](https://docs.camunda.io/optimize/next/self-managed/optimize-deployment/configuration/multi-tenancy/).

Operate could follow the same approach and document all the parameters in both formats.

**Comment by johanwelgemoed** [comment]
https://confluence.camunda.com/display/OPE/Configuration+variables

**Comment by johanwelgemoed** [comment]
@sdorokhova for this, would it be sufficient (as first step perhaps) to document that any of our parameters (yaml), can be used as environment variables by changing to `UPPERCASE` and replacing `.` with` _`? (and then obviously give an example for example as tasklsit does it in link in ticket above).

**Comment by sdorokhova** [comment]
@johanwelgemoed yes, this makes total sense!
We have [this sentence](https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/operate-deployment/operate-configuration.md?plain=1#L6) but it's not at all obvious how this can be applied. May be we replace this or append the information that you mentioned. As an option, instead of describing how to "convert" the parameter to env var, may be we can put [this link to Spring documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables)?
