### ISSUE TITLE
Inconsistent casing in technically relevant naming guidance

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3168]
In https://docs.camunda.io/docs/components/best-practices/modeling/naming-technically-relevant-ids/, it should be changed from camelCase to PascalCase

See https://github.com/camunda/camunda-docs/pull/3167

**Comment by HanselIdes** [comment]
@akeller can I get help from your team in backporting and pushing this with the next scheduled release?

**Comment by akeller** [comment]
@christinaausley, if you have the capacity, please have a look.

Otherwise, this will be triaged after the minor release.

**Comment by christinaausley** [comment]
@HanselIdes It looks like you backported this in https://github.com/camunda/camunda-docs/pull/3167 -- are there other references that need to be updated, or am I misunderstanding here?

**Comment by HanselIdes** [comment]
@christinaausley Nope, it looks like this can be closed out
