### ISSUE TITLE
Consolidate or restructure manage cluster section

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3199]
<img width="289" alt="image" src="https://github.com/camunda/camunda-docs/assets/1051363/28e3f082-7123-4436-aa07-c828a6f9b55d">

We don't need a dedicated page for each of these topics. This should be restructured in a way that it's intuitive how it will grow and where new content should live as the functionality changes.

**Comment by akeller** [comment]
@christinaausley this is probably a medium project, but it would be great to have a strategy (in collaboration with @jprcoliveira) for how this section will grow or change - new page or just a new section on an existing page.

**Comment by jprcoliveira** [comment]
@akeller we def need the input from the PM from Console aka @theburi

**Comment by christinaausley** [comment]
I like this project! @jprcoliveira I'll ping you when I'm ready to get started here, but feel free to ping me if you're already making movement here 👍 Can loop in @theburi.

**Comment by akeller** [comment]
@christinaausley, could you deliver this before 8.6?

**Comment by christinaausley** [comment]
Definitely!

**Comment by christinaausley** [comment]
@theburi I've launched a [Miro board](https://miro.com/app/board/uXjVKlUBhHM=/?share_link_id=670477227675) to discuss some options with this restructure -- let me know what you think 👍

**Comment by christinaausley** [comment]
Also going to loop in @akeller and @camunda/tech-writers -- I'll get around to your feedback and launch a PR with changes when I'm back from FTO in September 👍

**Comment by christinaausley** [comment]
@mesellings @conceptualshark I've shared the miro board with your emails -- let me know if you have any thoughts. CC @theburi

**Comment by theburi** [comment]
CC @felix-mueller doc change for SaaS

**Comment by christinaausley** [comment]
Hi all -- sharing a screenshot of my Miro thoughts below in the case there are strong opinions out there -- if not, will PR following release for additional conversation.

![Image](https://github.com/user-attachments/assets/ca0d1050-b803-458e-b6f6-84de23fa9483)

**Comment by christinaausley** [comment]
This was merged. Closing!
