### ISSUE TITLE
Document ElasticSearch required privileges for SM

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#3224]
## Summary

Some customers need to know which privileges C8 applications requires when accessing a locally set-up ES. This allows them to fine-tune the permissions they grant. 

## Problem

Currently, this list of privileges is not discoverable in the docs. We have ad-hoc collected this list (see https://camunda.slack.com/archives/C026U8GBNSW/p1705485613567079?thread_ts=1705068753.577989&cid=C026U8GBNSW), but should document this in a central place discoverable for our users.

**Comment by akeller** [comment]
How quickly should we move on this? We can PR the current, ad-hoc list or wait for a consolidated and verified list.

**Comment by MaxTru** [comment]
> How quickly should we move on this? We can PR the current, ad-hoc list or wait for a consolidated and verified list.

The list is now complete and verified ([ref](https://camunda.slack.com/archives/C06E913HYTE/p1705698715623889?thread_ts=1705487280.018669&cid=C06E913HYTE)). No need to rush though, but this could be an easy quick win.

**Comment by johanwelgemoed** [comment]
@MaxTru I think we should preemptively create/verify a similar list for OpenSearch. If you agree then I will reach out to Roman (for starters I think), or whoever else can help me.

**Comment by akeller** [comment]
@johanwelgemoed this is a great idea, and likely a best practice for any permissions/privileges we have moving forward. I assume this will continue to come up during things like perspective customer questionnaires.
