### ISSUE TITLE
Document batch modification in Operate user guide

### ISSUE THREAD

**Issue by pedesen** [camunda/camunda-docs#3233]
### Description

Operate will introduce batch move modification. This will be documented in the Operate user guide.

Following functionality should be covered for the user interface:

- How to select flow nodes to enter batch migration
- How to select target flow node
- How to trigger the modification operation
- Add a link to "Monitor operation status" section (see https://github.com/camunda/camunda-docs/issues/3654)

Also mention that the same limitations as for single move modification apply, which means the following elements cannot be used, neither as source nor as target elements:
  - start events
  - boundary events
  - multi instance tasks
  - elements attached to an event based gateway
 
### TODO

- [x] Add documentation and cover functionality mentioned above

### Related Operate issue

https://github.com/camunda/operate/issues/5872

**Comment by christinaausley** [comment]
Hi 😄 Should I be on the lookout for any additional changes with this this week?

**Comment by pedesen** [comment]
@christinaausley No, this feature will not be part of 8.5.0, but 8.6.0-alpha1, I updated the label accordingly.
