### ISSUE TITLE
Consolidate pages in Self-Managed

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3235]
We should be able to introduce this overall Self-Managed section of the docs and the architecture of the platform within the same page. 

We also have redundant content across the Architecture > Overview and Installation > Overview.

Possible solution(s):

* Consolidate 2 pages into 1 single page the introduces the SM docs section and architecture of Self-Managed:
  * https://docs.camunda.io/docs/self-managed/about-self-managed/
  * https://docs.camunda.io/docs/self-managed/platform-architecture/overview/

* Consolidate some information across the following 3 pages:
  * https://docs.camunda.io/docs/self-managed/about-self-managed/
  * https://docs.camunda.io/docs/self-managed/platform-architecture/overview/
  * https://docs.camunda.io/docs/self-managed/platform-deployment/overview/

**Comment by akeller** [comment]
@christinaausley this may be a good task for you to pick up if you are interested in some content consolidation work.

**Comment by aabouzaid** [comment]
I'd suggest waiting till this epic is done
https://github.com/camunda/distribution/issues/145

Also, we need to keep the architecture section because it will have more pages in the 8.6 release cycle (e.g. multi-namespace, multi-region, etc).

**Comment by akeller** [comment]
@aabouzaid is this something you are working on with @theburi? See my comment on your linked issue. 

For large documentation restructures, please keep us informed so we can collaborate. Where can I learn more about your goals or vision for this with 8.6?

**Comment by akeller** [comment]
Assigning this to @conceptualshark given their focus on SM topics.
