### ISSUE TITLE
Document New Context Menu

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-docs#3243]
Once we've rolled out the new context menu so it can be enabled as an alpha feature we have to have it documented somewhere so users can find out what they're enabling before doing so. The documentation will be accessible from where the feature is enabled or disabled.

![image](https://github.com/camunda/camunda-docs/assets/7633572/7e97a8dd-4cb7-4e12-8b0d-479bdcf7c437)

An existing example of a documented alpha feature is Play: https://docs.camunda.io/docs/components/modeler/web-modeler/play-your-process/

---

Related to https://github.com/camunda/product-hub/issues/1505

**Comment by akeller** [comment]
I've added some new component labels to help DevEx know when we should expect a feature to be released (and, therefore, how to prioritize docs reviews, merge, etc.).

For this epic, would it also include `web-modeler-sm`? Will it be released together as part of an alpha or minor?

**Comment by philippfromme** [comment]
https://github.com/camunda/web-modeler/pull/7847 is now in review. I will start working on documentation.
