### ISSUE TITLE
Create Tutorial to use Tasklist REST API

### ISSUE THREAD

**Issue by houssain-barouni** [camunda/camunda-docs#3247]
Today we have this [Tutorial](https://docs.camunda.io/docs/apis-tools/tasklist-api/tasklist-api-tutorial/) explaining how to build a BFF on top of Tasklist GraphQL API.
We also have a [GraphQL to REST API migration guide](https://docs.camunda.io/docs/apis-tools/tasklist-api/tasklist-api-graphql-to-rest-migration/).

We need a new tutorial explaining how to build a BFF on top of Tasklist REST API, for clients starting from scratch.

**Notes**: 
- for 8.5 we will start building Tasklist REST API V2, that needs to be used along with Zeebe user tasks REST API. This may need to be tackled in a new ticket.
-  let's also document how to do an eligibility check for "complete" - i.e. compare user with task assignee before granting access to complete, since the API does not check this

**Comment by christian-konrad** [comment]
@houssain-barouni let's also document how to do an eligibility check for "complete" - i.e. compare user with task assignee before granting access to complete, since the API does not check this. (There was a question just now: https://camunda.slack.com/archives/C0622NWC9LK/p1710927920290469)

**Comment by houssain-barouni** [comment]
Hi @christian-konrad ,
I have got some bandwidth to work on this tutorial this week

I was thinking of having as subject: building a Java backend client for Tasklist/Zeebe REST apis, to manage Zeebe user tasks, the recommended user task implementation starting from 8.5.

- The java app will use Zeebe's [spring-boot-starter-camunda-sdk](https://github.com/camunda/zeebe/tree/main/spring-boot-starter-camunda-sdk)
- We don't have yet an official Tasklist API sdk, so I will explain how they can generate an API client with all the required datamodel from Tasklist OpenApi specs 
- I will explain how to manage authentication to Zeebe and Tasklist APIs for local and SaaS
- I will showcase a script scenario:
  - deploy a process containing a Zeebe user task, then start process instances
  - use Tasklist API to search for Tasks
  - use Zeebe API to assign a user to a Task
  - use Tasklist API to get the assigned task
  - complete the task with eligibility check that you have requested
  - use Tasklist API to search for completed Tasks

Does it sound good for you? If yes, I can work on a sample app that you can play with

**Comment by christian-konrad** [comment]
@houssain-barouni this is great! I'd love to see this. 
The one thing I'd probably add is having notes about async/event driven behavior of our APIs/Zeebe, i.e. to get real-time updates when a task is created, users can write a custom exporter. 
Why? We got a multitude of questions and complaints about the 5 sec delay until a task is available, and users expected sync, transactional behavior. A note should make clear it's async, tasks appear later, and to subscribe to task creation, use an exporter.
