### ISSUE TITLE
Postman Collection - Optimize and Operate do not contain request body

### ISSUE THREAD

**Issue by McAlm** [camunda/camunda-docs#3264]
Our Camunda Postman Collection for the Optimize and Operate API does not contain the request body, e.g. for Optimize:
**/api/public/import?collectionId**

One has to search the docs for the correct request payload, what makes this collection unusable. As developer I'd like to have a Postman collection with complete request json structure and example requests as shown in [Tasklist Public API (REST)](https://www.postman.com/camundateam/workspace/camunda-8-postman/collection/26079299-f0db0193-0557-4acd-8e94-ecdaeffbaa5d?action=share&creator=6569596) or [Console API (REST)](https://www.postman.com/camundateam/workspace/camunda-8-postman/collection/20317927-4c378140-b9ca-4f2d-b4d5-479ab0fcc472?action=share&creator=6569596).

**Comment by christinaausley** [comment]
@pepopowitz Interested in pairing on this? If so, I'll pop some time on our calendar to discuss with https://github.com/camunda/developer-experience/issues/224 next week.

**Comment by pepopowitz** [comment]
Yes, schedule something!
