### ISSUE TITLE
Update link to product

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3271]
The footer points the user to Console, but users are being sent to Web Modeler instead. This link should show "Web Modeler" instead (I would say Modeler, but in this case it's still ambiguous with Desktop Modeler)
![image](https://github.com/camunda/camunda-docs/assets/17521551/5cf00007-61da-49bc-b37e-d5ba688e2e59)

**Comment by HanselIdes** [comment]
I wanted to add this to the DevEx team backlog for whenever you want to get to it

**Comment by akeller** [comment]
@christinaausley a quick win opportunity if you'd like to grab it.
