### ISSUE TITLE
Document the Zeebe OpenAPI spec

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#3277]
### Description

With https://github.com/camunda/product-hub/issues/1926, Zeebe will provide its very own REST API.

The REST API endpoints should be documented in the Camunda 8 documentation. Preferably, the REST API endpoint docs are generated from the [Zeebe OpenAPI specification document](https://github.com/camunda/zeebe/blob/main/zeebe/gateway-protocol/src/main/proto/rest-api.yaml).

### Additional context

- Some clarifications on this task, and some ideas on how to implement it can be found [here](https://docs.google.com/document/d/1IxHvRBNa6VtQN53QjbHxfckD8mJqYxEuh5Uvza4pq80/edit#heading=h.4o91eke4a088)  (internal Google Doc)

**Comment by pepopowitz** [comment]
@koevskinikola I've created a separate issue for myself, https://github.com/camunda/camunda-docs/issues/3421, to track the implementation of the API Explorer. Do you want to keep this issue for your team, and have it represent the related non-generated documentation you'll be creating?

**Comment by koevskinikola** [comment]
Hey @pepopowitz, yes I'll keep this one for any manual docs required for the OpenAPI. If it turns out we don't need it, I'll close it later. Thanks!

**Comment by megglos** [comment]
will be closed by https://github.com/camunda/camunda-docs/pull/3487

**Comment by npepinpe** [comment]
Assigning myself to it to keep track of closing it.

**Comment by npepinpe** [comment]
Authentication will look pretty much like Tasklist, with some minor changes (e.g. example API calls, no cookie support, etc.). But otherwise very similar.

**Comment by pepopowitz** [comment]
@npepinpe I've added an Authentication page in #3529. Please review there to make sure my changes are accurate. (The page can be seen [here in the preview site](https://loquacious-pika-a05ac2.netlify.app/docs/next/apis-tools/zeebe-api-rest/zeebe-api-rest-authentication/), or [here for the commit itself](https://github.com/camunda/camunda-docs/pull/3529/commits/3239fa9790a827716f8422856aa0424c592f2b95)).

**Comment by npepinpe** [comment]
Done thanks to @pepopowitz I've opened some PRs related, but it's been split into multiple things now.
