### ISSUE TITLE
Aurora is missing from Identity in Support environments

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3329]
[Aurora](https://docs.camunda.io/docs/self-managed/identity/deployment/configuration-variables/#running-identity-on-amazon-aurora-postgresql) is missing from the Identity row on the [Supported environments page](https://docs.camunda.io/docs/next/reference/supported-environments/#camunda-8-self-managed).

It's unclear what versions are supported, but here are possibilities:

* Same as Web Modeler - Amazon Aurora PostgreSQL 13.x, 14.x, 15.x?
* Only 14.x and 15.x, like PostgreSQL for Identity?
* Or something else?

Internal Slack thread - https://camunda.slack.com/archives/CRQAL5A1M/p1707846527383299

**Comment by Ben-Sheppard** [comment]
Hi @akeller - the [Identity compatibility checks for Aurora](https://github.com/camunda-cloud/identity/blob/main/.github/workflows/compatibility-check.yml#L155-L161) currently test version 13, 14, and 15
