### ISSUE TITLE
Remove Web Modeler beta API content

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3362]
"Web Modeler's beta API is deprecated and will be removed in the 8.5 release of Web Modeler."

We should remove all references to the beta API in 8.5 and onward.

**Comment by christinaausley** [comment]
@HanselIdes It looks like this was handled in a few incoming PRs for release -- anything else you need from us here?

**Comment by HanselIdes** [comment]
@christinaausley Nope, I have no additional needs
Enjoy the release excitement! 🙃
