### ISSUE TITLE
CreateProcessInstanceWithResultRequest.fetchVariables missed in Zeebe GRPC docs

### ISSUE THREAD

**Issue by dimastbk** [camunda/camunda-docs#3367]
Hi!

`CreateProcessInstanceWithResultRequest.fetchVariables` is missing from Zeebe GRPC docs. Protobuf: https://github.com/camunda/zeebe/blob/86828ff3fd3caef48b3229c1f717466b35c955eb/gateway-protocol/src/main/proto/gateway.proto#L157-L166, docs: https://github.com/camunda/camunda-docs/blob/0737c81504df0f8e132aea11ecef0304d753ba5d/docs/apis-tools/zeebe-api/gateway-service.md?plain=1#L306-L312

**Comment by akeller** [comment]
Following up internally - https://camunda.slack.com/archives/CSQ2E3BT4/p1708969348168679

**Comment by akeller** [comment]
This was added initially as `CreateWorkflowInstanceWithResult` and then renamed to `CreateProcessInstanceWithResult`.

We need to add it here - https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#createprocessinstancewithresult-rpc, confirming the input, output, and errors are correct.
