### ISSUE TITLE
Entry page for all user task migration enablement material

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3382]
Provide a single entry page for all user task migration enablement material.

Ideally, it's the migration guide page.

It should link to all things like decision helper, API docs (of both APIs), user task docs, modeling guide...

**Comment by akeller** [comment]
@christian-konrad just added this to the HTO Team board for you so it doesn't get lost

**Comment by christian-konrad** [comment]
Done in #3423
