### ISSUE TITLE
Zeebe REST API Explorer

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#3421]
Implement an API Explorer for the Zeebe REST API.

Deadline: April release

Part of, or related to, https://github.com/camunda/camunda-docs/issues/3277.

## Implementation notes

* The OpenAPI spec is available at https://github.com/camunda/zeebe/blob/main/zeebe/gateway-protocol/src/main/proto/rest-api.yaml
* Any updates to the spec can be PR'ed directly there ☝️ 
* Documentation outside of the API Explorer (e.g. authentication) will be handled by the Zeebe REST team. 

## Acceptance criteria 

* The API itself is currently in alpha. The API Explorer, and navigation to/from it within the docs, should make this clear. When we release 8.5 in April, the API will move to general availability, and the API Explorer should then reflect that.

**Comment by akeller** [comment]
Moving this to `In Progress` since there is an open PR
