### ISSUE TITLE
Create migration guide to Zeebe User Tasks

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3423]
With the introduction of Zeebe User Tasks and the Zeebe Task API, we need to enable partners and customers to migrate their task applications.

We need to
- Explain under which circumstances they have to migrate, and what it includes
- Help them decide when to migrate and to estimate the impact on their project
- Describe the steps needed to take

**Comment by akeller** [comment]
@christian-konrad do you have an idea of where to put this information? Are you thinking a user guide in Guides or APIs & Tools?

**Comment by christian-konrad** [comment]
@akeller I put it under guides (next to the C7 migration guide), do you think it should be better in the API space?

I wasn't sure since the guides are meant to be quite introductory and this migration guide is actually not relevant for new users
