### ISSUE TITLE
Rephrase "personal organization"

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3469]
Here's a small item to clean up when you have time

https://docs.camunda.io/docs/components/console/manage-organization/manage-users/ mentions a "personal organization". This introduces a new term into the Camunda docs and might discourage users from inviting their colleagues to make it a shared company organization.

`When a user signs up for Camunda 8, they receive a personal organization. Clusters the user creates in this organization are assigned to this organization.

If several users need access to the same Zeebe cluster, all users can be assigned to the same organization.`
could be changed to:

`When a user signs up for Camunda 8, they become the owner of a Camunda organization. This organization owns Modeler files and Zeebe clusters. The owner and any admins they assign can control access to these resources through managing their organization.`

**Comment by akeller** [comment]
This seems related to https://github.com/camunda/camunda-docs/issues/3461. @felix-mueller would we address these together?

**Comment by felix-mueller** [comment]
Its related but we can make progress on this item here independently.

**Comment by akeller** [comment]
@christinaausley assigning this to you since it's based on language and term use.
