### ISSUE TITLE
Consolidate troubleshooting pages in SM

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3475]
Related to https://camunda.slack.com/archives/C06KJS0PJ94 and slicing this PR smaller for speed and easier delivery

**Comment by akeller** [comment]
I _think_ we reduced the number of troubleshooting pages we have already, but can you double-check @conceptualshark? If this isn't an issue anymore, you can just close the issue.

**Comment by conceptualshark** [comment]
Based on [this PR](https://github.com/camunda/camunda-docs/pull/3479) it looks like a majority of the work intended here was handled - I'm going to go ahead and close this.
