### ISSUE TITLE
Add simple page rating

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#355]
https://twitter.com/sebastienlorber/status/1433355345754263553

A simple page rating system would help us better understand what pages need to be evaluated for updates. 

Using Google Analytics, we can create a simple button system (thumbs up, thumbs down).

**Comment by akeller** [comment]
@pepopowitz I know I've casually mentioned this, but I think this is one of the bigger items I'd like you to tackle. From what Sebastien Lorber (core maintainer for Docusaurus) said, it's allegedly straightforward. 

For extra context, this is step one in providing a mechanism for collecting data on docs pages beyond vanity metrics available in Google Analytics. @christinaausley can chat more about what we've looked at with GA so far and where we want to take it towards making more data-driven docs decisions.

Step two is a commenting system, but that's out of the scope of this issue. Together these items would probably make a good DX + Docs Infra talk or blog topic (why, how, how's it going). Something to keep in mind 😄

**Comment by pepopowitz** [comment]
Yeah this looks like a super fun "bigger project." Looking forward to digging into this one.

**Comment by akeller** [comment]
Moving this to the backlog since I don't think it will be worked on in Q4.

**Comment by akeller** [comment]
I still really like this idea for iterating on specific pages, but we just haven't found time for it.

I like Airbyte's implementation on their docs - https://docs.airbyte.com/

It sits in the right-side TOC area for the page 
<img width="162" alt="image" src="https://github.com/camunda/camunda-docs/assets/1051363/ba40f521-9c2e-4fa4-bc58-f438966a7bd2">

If you hit thumbs up or thumbs down, a "Thank you" renders where the thumbs were. This might be due to my network configuration, but on thumbs down, it would be cool to see a short survey or text box for a short description pop up. Bonus points if we tie it into the forum.

**Comment by christinaausley** [comment]
@pepopowitz want to pair on this? Would Q1 of 2024 work for you?

**Comment by dgarcia360** [comment]
Hello @akeller, @christinaausley, and @pepopowitz,

I found this issue while searching for "docs rating" on GitHub. I'm the founder of [PushFeedback](https://pushfeedback.com/), a feedback widget designed specifically for documentation sites that integrate well with [Docusaurus](https://docs.pushfeedback.com/installation/docusaurus).

![](https://github.com/camunda/camunda-docs/assets/9107969/ba1cdc90-6dfc-44f9-98dd-6a4126c20d21)

We offer a complimentary plan for open-source projects, which includes full access to our features while retaining the PushFeedback branding. If you're considering adding a feedback mechanism to your docs, I invite you to [create an account](https://app.pushfeedback.com/accounts/signup/). Once you're set up, please let me know, and I'll remove the limitations for your docs project.

Looking forward to hearing from you!

**Comment by christinaausley** [comment]
@pepopowitz Want to collaborate on this in May? I'll likely begin researching options May 6-10, and we can share notes/outline an implementation plan via Zoom sync the week of May 13-17?

If you're interested, I'll send you a meeting invite and get a Miro going for async research.

**Comment by christinaausley** [comment]
Based on my collected proposals in [Miro](https://miro.com/app/board/uXjVKKMeuk4=/?share_link_id=642834874723), got the thumbs up from @pepopowitz today to move forward with testing PushFeedback 🥳 

@dgarcia360 -- I'm planning to create an account this week or next week to test the feature in our documentation as a heads up. My email is christina.ausley@camunda.com, if you'd like to correspond that way.

**Comment by dgarcia360** [comment]
@christinaausley Awesome! Please let us know if you need any help with the configurations. We're here to help!

**Comment by christinaausley** [comment]
@pepopowitz and I to meet next week to polish up the CSS -- will submit a ticket to https://helpdesk.camunda.com/support/home next week as well 👍

**Comment by christinaausley** [comment]
Note that this has been approved from an InfoSec and Compliance side -- submitted a purchase order today. In the homestretch!

**Comment by christinaausley** [comment]
Purchase order and spend limit approved -- merging this in tomorrow 👍

@akeller Once I upgrade, I'll add the DX team. Any other teams you'd like me to reach out to? PMs?

**Comment by akeller** [comment]
Let's start with DevEx only and if we see patterns and trends emerging, pull in other teams or individuals with the appropriate context.

**Comment by christinaausley** [comment]
See https://camunda.slack.com/archives/C047D95HBE2/p1721748135768159 for additional context.
