### ISSUE TITLE
Optimize migration instructions does not match with default configuration description

### ISSUE THREAD

**Issue by timstawowski** [camunda/camunda-docs#3634]
In [Update notes (3.10 to 8.3/3.11) > Changes in behavior> Collection Role Cleanup](https://docs.camunda.io/optimize/self-managed/optimize-deployment/migration-update/3.10-to-3.11_8.3/#collection-role-cleanup) it is mentioned that the default behavior of the collection role cleanup is now disabled by default, which does not match the description in [Camunda 7 common import settings](https://docs.camunda.io/optimize/3.11.0/self-managed/optimize-deployment/configuration/system-configuration-platform-7/) saying the default value of `import.identitySync.collectionRoleCleanupEnabled` is `true`.

**Comment by akeller** [comment]
Thanks, @timstawowski. I've reached out internally to the Optimize team to verify and update. 

Internal Slack thread - https://camunda.slack.com/archives/C55U06YRG/p1712676082097069

**Comment by akeller** [comment]
Confirmed with Optimize team -

> The correct default would be false.

Will open a PR to resolve this.
