### ISSUE TITLE
Remove note in forms docs that forms have a minimal feature set

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-docs#3646]
Remove note in forms docs that forms have a minimal feature set (they don't :) anymore)

<img width="1094" alt="Bildschirmfoto 2024-04-10 um 11 57 54" src="https://github.com/camunda/camunda-docs/assets/56470362/df95ca84-7cae-40cd-a42d-67f7a99c4854">

**Comment by akeller** [comment]
Adjusting this for 8.5 and 8.6
