### ISSUE TITLE
Update screenshots for "create-cluster" to show latest generation naming

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#3668]
**Problem**

The https://docs.camunda.io/docs/next/components/console/manage-clusters/create-cluster/ page currently shows screenshots highlighting the "old" cluster-generation naming.

Since 8.5 we have a new naming pattern - see https://docs.camunda.io/docs/next/reference/announcements/#camunda-saas-new-generation-naming-scheme.

This can create confusion: the user finds a different situation when creating clusters in practice compared to the docs.

**Improvement suggestions**

Update the screenshots.

**Comment by akeller** [comment]
@christinaausley @ultraschuppi, this screenshot is part of Console's screenshot automation, correct? Who can get this updated?

**Comment by ultraschuppi** [comment]
we can run an update of the automated screenshots for console - this will be done during https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2704

it might take a bit of time though, since a couple of selectors have changed and we need to bring them back into shape

**Comment by akeller** [comment]
If we get any further internal or external comments on this, we can add a temporary screenshot adjustment, but I think it's ok to wait for now.

**Comment by ultraschuppi** [comment]
@akeller this should do the trick: https://github.com/camunda/camunda-docs/pull/3683
