### ISSUE TITLE
Missing "Release date" and "end of maintence" for 8.5 release on announcements page

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#3673]
**Problem observed**

The 8.5 release does not specify a "release date" and "end of maintenance" date on the announcements page.

**How to recreate**

* Visit https://docs.camunda.io/docs/next/reference/announcements/#camunda-85.
* Compare 8.5 release with 8.4 or previous releases

**Improvement suggestion**

* Add these fields for 8.5 as well

**Comment by akeller** [comment]
Will add this to my list to do today, along with 8.6 in `/next/`.

**Comment by akeller** [comment]
@oleschoenburg covered this in https://github.com/camunda/camunda-docs/pull/3660 🙌 

I will create a separate PR to add it to 8.6.
