### ISSUE TITLE
Identity values in OIDC configuration use confusing step links

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda-docs#3676]
### Description
In the [documentation](https://docs.camunda.io/docs/self-managed/setup/guides/connect-to-an-oidc-provider/) for connecting to an OIDC provider using helm values, for identity it says `<Client ID from Step 2> and <Client secret from Step 2>`, while for all other components it says <Client ID from Step 1> <Client secret from Step 3>.

### Proposed solution
The Identity documentation should be aligned with the other components and correctly reflect the reference location for the values.

**Comment by akeller** [comment]
@Ben-Sheppard is this something the Identity team will handle? If so, please add it to the team project board.

**Comment by Ben-Sheppard** [comment]
Hey @akeller - it can be handled by the team but can be handled by anyone really, I can't add it to the Identity team project board because we aren't in the same Org.
