### ISSUE TITLE
cluster-creating-model includes option for backup location

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3684]
Since this new screenshot includes a backup location option, we should review the docs where it's used and add a brief mention so users are aware it is available through this UI. 

> This new screenshot includes backups.

_Originally posted by @akeller in https://github.com/camunda/camunda-docs/pull/3683#discussion_r1571004668_

**Comment by ultraschuppi** [comment]
backups docs have been sitting here for some while: https://docs.camunda.io/docs/8.4/components/concepts/backups/

**Comment by akeller** [comment]
Happy to see the conceptual docs, but we got a very timely message on this - https://camunda.slack.com/archives/C026U8GBNSW/p1713520071233019

We can add a brief sentence so customers know where to look in the UI.

**Comment by ultraschuppi** [comment]
to look for what?

**Comment by akeller** [comment]
> to look for what?

The toggle for backup docs in the UI.

**Comment by ultraschuppi** [comment]
> > to look for what?
> 
> The tab for backups in the UI.

yeah well, i personally don't think that's worth documenting - because people still have brains and common sense and what not. but WDIK ;)

**Comment by akeller** [comment]
Some people use the docs for internal vendor questionnaires. So we'll add it 😄

**Comment by ultraschuppi** [comment]
> Some people use the docs for internal vendor questionnaires. So we'll add it 😄

O_o

nobody will be able to keep track and keep things up to date if we really document _everything_. how about a screenshot of the tab? is anyone going to remember that there is a screenshot of that tab in the docs that needs to get updates because of _we are making use for internal vendor questionaires_?
