### ISSUE TITLE
Audit docs for scopes within client credentials modal

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3686]
Since this screenshots shows changes, we should make sure the surrounding docs are updated to reflect what can be found in this modal.

> Screenshot shows cluster update was added and Web Modeler API was removed. May need to check how the docs describe this.

_Originally posted by @akeller in https://github.com/camunda/camunda-docs/pull/3683#discussion_r1571001371_

**Comment by ultraschuppi** [comment]
> Screenshot shows cluster update was added and Web Modeler API was removed

there is a scrollbar in the modal and likely it is just in the uncaptured area ;-)

**Comment by akeller** [comment]
Wow, I really had to zoom in to see that very small, faded area. Thank you for confirming!
