### ISSUE TITLE
Audit docs for home screenshot changes

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#3687]
The home screenshot doesn't show the onboarding experience anymore. Confirm this is as expected and adjust the docs surrounding this screenshot if necessary.

> This looks a bit different. This won't block my approval and merge, but we should follow up.

_Originally posted by @akeller in https://github.com/camunda/camunda-docs/pull/3683#discussion_r1571003254_

**Comment by ultraschuppi** [comment]
this is gone for good ;)

**Comment by akeller** [comment]
BYE! Closing 😉
