### ISSUE TITLE
Camunda Saas: Mention Zeebe REST API endpoint schema

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-docs#3698]
For other components, our docs state how the api endpoint is composed.

Example: https://docs.camunda.io/docs/next/apis-tools/tasklist-api-rest/tasklist-api-rest-overview/#swagger-ui

For zeebe, this is missing.

I would like to see this documented.

Context: https://camunda.slack.com/archives/CSQ2E3BT4/p1713784273287589

**Comment by tmetzke** [comment]
As far as I know, there is no out-of-the-box Swagger UI endpoint in the Zeebe REST API. Thus, it cannot be documented. Please correct me if I'm wrong, @npepinpe.

**Comment by npepinpe** [comment]
Or do you want something else?

**Comment by jonathanlukas** [comment]
No, I don't swagger or anything. I just want to see a section like this:

The root context for the zeebe rest api can be found:
* for Saas: `https://${REGION}.tasklist.camunda.io:443/${CLUSTER_ID}`
* for Self-Managed: `http://localhost:8080`

**Comment by tmetzke** [comment]
Thanks, @jonathanlukas, for clarifying 🙂

**Comment by tmetzke** [comment]
Funny enough, the other components don't tell you this either. They just state where the Swagger UI resides.

**Comment by akeller** [comment]
For years I've tried getting this (for all components) in the docs and Console Connection information. 🙏  Pave the way Zeebe REST API! 🚀

**Comment by tmetzke** [comment]
> For years I've tried getting this (for all components) in the docs and Console Connection information. 🙏 Pave the way Zeebe REST API! 🚀

As the change doesn't seem that big in terms of lines to write, have there been any arguments against doing this, @akeller?

**Comment by akeller** [comment]
@tmetzke at one point there was a debate around regions and ports, but no arguments against. If it changes in the future, we can update the docs.

**Comment by tmetzke** [comment]
Well, I could see how this could become inaccurate for SM at least real quick, but we can add a disclaimer and just state that this depends on your config but resides at `http://localhost:8080` by default.

**Comment by tmetzke** [comment]
So, is this what we'd like to see for Tasklist and Zeebe, for example? I added a `Context paths` section.

## Tasklist
![image](https://github.com/camunda/camunda-docs/assets/586643/c518ba6a-bb55-422b-8220-5ececf3e8e0c)

## Zeebe
![image](https://github.com/camunda/camunda-docs/assets/586643/610fb949-93b9-45b2-852b-b5b75097239d)

**Comment by tmetzke** [comment]
Created a PR for this: https://github.com/camunda/camunda-docs/pull/3710
