### ISSUE TITLE
Configuration file links broken and unversioned

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#3744]
The links to the configuration files are currently broken:
https://github.com/camunda/camunda-docs/blob/a644fe5c72a56e94409b13b65fb5733a3dd75a84/docs/self-managed/zeebe-deployment/configuration/configuration.md?plain=1#L34-L37

While the Zeebe source code has been moved to a sub-folder the `dist` folder has not moved, i.e. the files are still here: https://github.com/camunda/zeebe/tree/main/dist/src/main/config

In addition, the files for older versions are available in tags, e.g. https://github.com/camunda/zeebe/tree/8.5.0/dist/src/main/config

So, the versioned docs should link to the corresponding tag or users will have surprises trying to use configuration parameters that don't exist in older versions.

Also the Camunda Docs AI does not know about the contents of these configuration files and can therefore can't answer questions like: 
> What does ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_NUMBER_OF_SHARDS?

**Comment by akeller** [comment]
@christinaausley can I have you take a look at the link component of this issue in the next two weeks? Having the right versioned links in the docs for each minor makes sense.

Regarding the Camunda Docs AI, we can split this into a separate issue on the Developer Experience repo and explore how we want to handle it. We don't ingest repos, but it might be a point to start that conversation or trial very specific files with config values (and, likely, inline docs).

**Comment by christinaausley** [comment]
This is done! Closing.
