### ISSUE TITLE
User Task Access Restrictions don't explain SM

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#3779]
# Description

User Task Access Restrictions don't explain how to configure them in SM.

# Reproduce

Visit https://docs.camunda.io/docs/next/components/concepts/access-control/user-task-access-restrictions/#enablingdisabling-user-task-access-restrictions.

=> You will learn how to configure the feature in SaaS, but not in SM.

# Expected behavior

In https://docs.camunda.io/docs/next/components/concepts/access-control/user-task-access-restrictions/#enablingdisabling-user-task-access-restrictions explain (or link to other page) allowing users to find out how to configure this feature in SaaS or in SM.

**Comment by christinaausley** [comment]
At large -- how do we ensure feature/docs parity between SaaS and SM moving forward?

**Comment by christinaausley** [comment]
@MaxTru I located this in https://docs.camunda.io/docs/next/self-managed/concepts/access-control/user-task-access-restrictions/, which also links to https://docs.camunda.io/docs/next/self-managed/identity/deployment/configuration-variables/#feature-flags.

Are you looking for additional guidance in this documentation, or can we close this out with the assumption I'll double check feature parity between SaaS and SM where applicable in the Product Hub moving forward?

**Comment by MaxTru** [comment]
Ah! Did not know of this page.

Should we not adjust https://docs.camunda.io/docs/next/components/concepts/access-control/user-task-access-restrictions/#enablingdisabling-user-task-access-restrictions to state:
* This is how you do it in SaaS (existing screenshot)
* This is how you do it in SM => Link to  https://docs.camunda.io/docs/next/self-managed/concepts/access-control/user-task-access-restrictions/

(Assuming that the concepts pages are saas/sm independent?)

**Comment by christinaausley** [comment]
I'll launch a PR for your review 👍
