### ISSUE TITLE
Document Help Center

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3816]
## Task Description
When getting started with Camunda, I want to learn about the Help Center so I know how to get information

## Implementation Notes
* Users who read the getting started guides should not be surprised by the signup/onboarding survey
* Users should know where the Help Center is available
  * Console
  * Modeler
  * Not in Tasklist, Operate, or Optimize
  * SaaS-Only (no SM)
* Users should get a brief description of each section of the Help Center
  * The "Recommendations" tab shows a set of recommended resources and next steps based on their signup or in-app onboarding survey
  * The "automation project guide" tab provides a set of recommended docs page for each phase of an automation project with Camunda SaaS
  * The "use case guide" tab provides a few getting started templates that new users should try
  * The "Camunda Academy" tab introduces the Academy and some of the reasons to go there to learn more
  * The "share your feedback" tab gives you a quick and easy way to share product feedback, suggestions, or bug reports that goes directly to Camunda's Product Management team.
* The links to the documentation and forum do not need to be documented
* One screenshot would be helpful to help orient people

<img width="769" alt="image" src="https://github.com/camunda/play/assets/17521551/fd695e2a-9b54-436c-be1e-b14927d3f85f">

## Links to additional collateral
Original epic: https://github.com/camunda/product-hub/issues/556
* See the "User Stories" and user narrative in the "Implementation Notes" section

**Comment by christinaausley** [comment]
Hi @HanselIdes -- planning to draft this up this week.
