### ISSUE TITLE
Best Practices claim Migration in C8 unsupported but it is

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#3823]
[Process Instance Migration is supported in C8](https://docs.camunda.io/docs/components/concepts/process-instance-migration/) therefore the Best Practices need updating:

https://github.com/camunda/camunda-docs/blob/60178187659c87a71bb1377097ceba7a24ef3957/versioned_docs/version-8.5/components/best-practices/operations/versioning-process-definitions.md?plain=1#L36-L38

**Comment by korthout** [comment]
Opened #3986 for some quick wins and opened #3987 to track the follow-up work.
