### ISSUE TITLE
Explain division of responsibilities

### ISSUE THREAD

**Issue by HanselIdes** [camunda/camunda-docs#3833]
Asked by [NN Bank](https://docs.google.com/document/d/1OpB2yW9jVgXvp1jex2PcfcKnEeA4b3FUWLYeResnXvg/edit) to have a link to documentation for them to refer back to.

What is the division of responsibility in SaaS option? – I am looking for a list of clear responsibilities of Camunda, Google Cloud and my company.
* Camunda is responsible for the SaaS in general. Updates, patches, bugs, disaster recovery, high availability and so on. 
* GCP is the place where Camunda SaaS is hosted, means, we rely on their SLAs for downtimes. There’s a health check provided for that. (shared with them on first meeting).
* You are responsible to manage the platform (add users, create projects, create API credentials, deploy processes, develop processes, create clusters, run processes etc.) 

* Does Camunda notify the customer if a cluster goes down?

Also for Self-Managed

**Comment by akeller** [comment]
@HanselIdes, this seems like a beefy topic that would probably be better suited for the [doc-hospital](https://github.com/camunda/doc-hospital). Are you (or another PM) driving this? Or does this issue represent the need for a driver as well?

**Comment by HanselIdes** [comment]
created here https://github.com/camunda/doc-hospital/issues/20 - I'll close this issue
