### ISSUE TITLE
Postman link in Optimize API links to Operate

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-docs#3848]
The link provided as part of the Optimize [Docs](https://github.com/camunda/camunda-docs/blob/main/optimize_versioned_docs/version-3.13.0/apis-tools/optimize-api/optimize-api-authentication.md#use-it-in-postman) might confuse users. We should remove it or link Optimize content.

**Comment by akeller** [comment]
Oops! Looks like just a copy & paste error. I would expect it to go to the Optimize API - https://www.postman.com/camundateam/workspace/camunda-8-postman/collection/24684262-a1103c05-7ed8-4fd4-8716-9005583ce23a
