### ISSUE TITLE
Document the upgrade version flow for self-managed

### ISSUE THREAD

**Issue by hamza-m-masood** [camunda/camunda-docs#3857]
**Describe the use case:**

It should be clear in our documentation on what version the customer should upgrade to next. We recommend to upgrade the latest patch release of the next minor version. 

For example, if the customer is on `9.2.0` then the customer should upgrade to `9.3.5` assuming that 5 is the latest patch release of the minor version 3.

**Desired outcome and acceptance:**
The above should be clear to our customers in our self-managed documentation.

**Comment by akeller** [comment]
Is this something the Distro team will take on? If you need assistance or collaboration, pull in @conceptualshark and we'll get it added on the DevEx board.

We have the following: 
> When updating from one minor version to the next, you do not need to update to each patch version along the way. However, do not skip minor versions when updating.

But it looks like you want more specifics about patches when, historically, we've focused on minors.

**Comment by hamza-m-masood** [comment]
@akeller  Just a small paragraph in [this page](https://docs.camunda.io/docs/self-managed/setup/upgrade/) about what I mentioned should suffice. I'm happy for @conceptualshark to take this issue. You can add me as reviewer.
