### ISSUE TITLE
Undocumented env var prefix `CAMUNDA_OPTIMIZE_`

### ISSUE THREAD

**Issue by falko** [camunda/camunda-docs#3863]
The documentation does not mention that corresponding environment variable names have to be prefixed with `CAMUNDA_OPTIMIZE_` for C8SM, e.g. `CAMUNDA_OPTIMIZE_EMAIL_ENABLED`:

https://github.com/camunda/camunda-docs/blob/73acda354feb4054655eb53e5449ba76c1146d0d/optimize/self-managed/optimize-deployment/configuration/system-configuration.md?plain=1#L247-L261

A prospect was not able to guess that on their own.

**Comment by akeller** [comment]
Thanks, @falko! I've assigned this to @conceptualshark to pick up, since it looks detailed enough.

FYI @RomanJRW

**Comment by falko** [comment]
This is another example of the general issue that customers have to use environment variables for our default installation path via Helm but the correct variable names are hard to guess from the configuration variables that are documented and also cannot be searched for.

**Comment by RomanJRW** [comment]
yes, we have some debt here. I would be happy to collaborate with @conceptualshark on making this clearer. I can support by providing the possible env vars that can be used in C7/C8SaaS/C8SM, and would leave the decision on how and where to document this with them

**Comment by conceptualshark** [comment]
Opted to resolve the original issue in this ticket, and take a deeper look at the gaps in the configuration here: https://github.com/camunda/camunda-docs/issues/3976
