### ISSUE TITLE
API tutorials don't make it clear where to capture environment variables from

### ISSUE THREAD

**Issue by pepopowitz** [camunda/camunda-docs#3915]
[Originated in Slack](https://camunda.slack.com/archives/C02UMKN3DTL/p1718048045153399), from @SamanthaHolstine.

In the API tutorials, we mention that users should create an API client, and we link them to the docs to do that. Later, we ask them to set the value of some environment variables that don't match the names of environment variables they received when creating the client. 

We should provide more explicit instructions that, for example, the value of `OPTIMIZE_CLIENT_ID` should come from the value of Zeebe client ID that they received upon creation of their client.

This applies to all current API tutorials (Administration, Optimize, and Modeler).

**Comment by christinaausley** [comment]
I think this is somewhat related to https://github.com/camunda/developer-experience/issues/247 -- @pepopowitz given your API rewrites would you still like an issue dedicated to capturing environment variables?
