### ISSUE TITLE
Update context pad docs to be latest instead of alpha

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-docs#3992]
Once we've rolled out the new context pad by enabling it by default for all organizations we should update the docs (https://docs.camunda.io/docs/components/modeler/web-modeler/new-context-pad/) to reflect that.

Related to https://github.com/camunda/product-hub/issues/1505

**Comment by philippfromme** [comment]
@crobbins215 to be done once you've enabled it.

**Comment by crobbins215** [comment]
@philippfromme , I plan on doing it on Monday next week

**Comment by philippfromme** [comment]
I'll prepare a PR.
