### ISSUE TITLE
Consolidate Intro to Camunda 8 + Intro to Components

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#4011]
As we move to position Camunda 8 as a unified platform, we should introduce Camunda 8 as a platform, not a set of components.

With that, we should consolidate [Introduction to Camunda 8](https://docs.camunda.io/docs/guides/) & [Introduction to Components](https://docs.camunda.io/docs/components/).

The final location is TBD - can be either the current location in /guides/ or /components/. 

--
This phase 2 item is part of the overarching project around #3988.

**Comment by christinaausley** [comment]
This is ready for review with [Consolidate intro to camunda #4181](https://github.com/camunda/camunda-docs/pull/4181), though note a few comments in the PR description for discussion.

**Comment by christinaausley** [comment]
@camunda/tech-writers @akeller I think the existing PR is a fine baseline and starting point for general ideas, but I should have started conversation on a Miro board before launching changes -- I'm going to convert this to a draft, and add a hold label.

See the [Miro board](https://miro.com/app/board/uXjVKm1QkNs=/?share_link_id=898204352738) for continued discussion, where I've outlined a second set of proposed changes. Will bring into the PR once finalized 👍
