### ISSUE TITLE
Add spring support policy for spring sdk

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-docs#4036]
Add spring support policy for spring sdk here: https://docs.camunda.io/docs/next/apis-tools/spring-zeebe-sdk/getting-started/#version-compatibility

https://camunda.slack.com/archives/C037W9NMATG/p1721203971434809

"For new minor releases we usually automatically update to new minor releases of our dependencies when they are released. This general rule also applies to spring. Thus, on main (8.6) we are already on spring boot 3.3.1"

**Comment by christinaausley** [comment]
This has been merged -- closing.
