### ISSUE TITLE
Microsoft Entra example helm config is not clear regarding redirect URLs

### ISSUE THREAD

**Issue by Ben-Sheppard** [camunda/camunda-docs#4066]
### Description
On the [docs page](https://docs.camunda.io/docs/next/self-managed/setup/guides/connect-to-an-oidc-provider/) regarding connecting to Microsoft Entra, we suggest in the helm example to `see table below` for the redirect URL, this is incorrect, the redirect URL in the table at the bottom of the page is the complete value that should be set in Microsoft Entra itself, the `redirectUrl` param in our helm chart example should actually be the root of the component. For example:

The redirect uri for Identity in entra could be `https://identity.example.com/auth/login-callback` but the `redirectUrl` value in our helm charts would be `https://identity.example.com`.

### Possible solution
The examples should be updated to correctly reflect the difference, and the table should perhaps be more descriptive about what the value is for.

**Comment by akeller** [comment]
@conceptualshark can you help the Identity team out with this one and add Ben as a reviewer?
