### ISSUE TITLE
Create an operational guide on how to tune Zeebe flow control

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda-docs#4087]
With the introduction of unified flow control and the new write rate limits, users might have questions how this works exactly and how to configure it correctly.

We should add an operational guide for self-managed users here: https://github.com/camunda/camunda-docs/tree/main/docs/self-managed/operational-guides

### Acceptance criteria

- [ ] The new page is organized under Self-Managed -> Operational guides
- [ ] The new page is only visible on 8.6 and later
- [ ] The title should mention "Flow control"
- [ ] All configuration options under `zeebe.broker.flowControl.write` are described
- [ ] We describe what "write rate" limits, i.e. all new records from processing results, new requests etc.
- [ ] We clarify that all limits apply on a per-partition basis
- [ ] We describe how processing behaves when limited by write rate, i.e. that it is slowed down when writing processing results
- [ ] We describe the user-facing effects of write rate limiting, i.e. increased backpressure, increased latency, decreased throughput
- [ ] We describe how the exporting rate is measured and how `zeebe.broker.flowControl.write.throttling.resolution` affects it.
- [ ] We describe how throttling is activated, depending on the exporting backlog
- [ ] We describe the expected effect of throttling on the exporting backlog
- [ ] We recommend to leave write rate limit (and throttling) disabled by default
- [ ] We recommend to enable static write rate limits to prevent throughput peaks
- [ ] We recommend to enable throttling to keep exporting backlog stable
- [ ] We recommend a high static write rate limit when throttling is enabled to avoid unnecessary limiting when exporting can keep up
- [ ] We explain and show the throttling annotation in our Grafana dashboard
- [ ] We point towards the right panels in our Grafana dashboard to observe exporting and write rate
- [ ] We point towards the right panel in our Grafana dashboard to observe exporting backlog
- [ ] We point towards the added panels that visualize the new flow control metrics
- [ ] We show how the flow control configuration can be changed temporarily via actuators
- [ ] The [backpressure page](https://github.com/camunda/camunda-docs/blob/main/docs/self-managed/zeebe-deployment/operations/backpressure.md) links to the new guide
- [ ] The [internal processing page](https://github.com/camunda/camunda-docs/blob/main/docs/components/zeebe/technical-concepts/internal-processing.md) links to the new guide

Out of scope:
* Describing anything under `zeebe.broker.flowControl.request`, these options are not new.
* Making suggestions on actual values such as `zeebe.broker.flowControl.write.limit`

**Comment by akeller** [comment]
This is easily the best-described acceptance criteria I've ever seen! 🤩 

@rodrigo-lourenco-lopes, if you need DevEx's assistance with structure or writing, you can reach out to @conceptualshark, our tech writer focused on the Self-Managed space.

**Comment by npepinpe** [comment]
So we have this page about back pressure that lives in a different place: https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/operations/backpressure/

Should we align them? They're related, after all. Should we move them both into the Operational Guides? Or should they both live in the `zeebe-deployment/operations`?

I would also propose cross linking them - i.e. put a note on each pointing to the other. Alternatively, we can combine them into a single guide about back pressure/rate limiting in general. What do you all think?

**Comment by npepinpe** [comment]
We also have this concept page talking about how to handle it - https://docs.camunda.io/docs/next/components/zeebe/technical-concepts/internal-processing/#handling-backpressure

It would make sense to me to briefly update here, as you may experience back pressure now not only because Zeebe is under high load, but because your secondary storage (e.g. Elastic) is under high load. So we should reflect that here at a minimum (thanks @alexcorremans :+1:)

**Comment by mesellings** [comment]
@rodrigo-lourenco-lopes Hi, how are you getting on with the docs for this? We have the alpha 4 release today, so if we are going to perform a review for you and merge it into the docs we ideally need it as soon as possible please? You can reach out directly to me on Slack for support, or let us know in the #ask-c8-documentation channel. 👍

**Comment by rodrigo-lourenco-lopes** [comment]
Hi @mesellings it is very unlikely that the PR will be ready and reviewed today. But we also don't require it for alpha 4, with the same justification as in [here](https://github.com/camunda/camunda-docs/pull/4136#issuecomment-2285637903).

**Comment by mesellings** [comment]
Hi @rodrigo-lourenco-lopes Thanks for the update, we will monitor it today 👍

**Comment by akeller** [comment]
Removing alpha4 label.
