### ISSUE TITLE
Potential typo in the Self-Managed Console Docs

### ISSUE THREAD

**Issue by jprcoliveira** [camunda/camunda-docs#4318]
Hi team, as I was looking how Self-Managed Console works I noticed that there might be a typo

Under the link below, should it read `Monitoring` instead of `Montioring`? 

https://docs.camunda.io/docs/next/self-managed/console-deployment/configuration/#montioring

**Comment by jprcoliveira** [comment]
FYI @christinaausley

**Comment by christinaausley** [comment]
Thank you @jprcoliveira for the catch!
