### ISSUE TITLE
Update the SM Licensing information for 8.6

### ISSUE THREAD

**Issue by conceptualshark** [camunda/camunda-docs#4356]
Licensing has changed in 8.6. The licensing page should reflect the new terms for each component (below), and the "enterprise only" badges/references should be removed from any impacted pages.

https://docs.camunda.io/docs/reference/licenses/

-- 

## Licensing[​](https://docs.camunda.io/docs/next/reference/licenses/#licensing)
This page contains licensing information for all components of Camunda 8 starting from version 8.6 and higher.

## Zeebe, Operate, Tasklist, Identity and Optimize
The source code for Zeebe, Operate, Tasklist, Identity, and Optimize is licensed to our users and customers under the [Camunda Licence v1](https://legal.camunda.com/licensing-and-other-legal-terms#camunda-license). 
The compiled software of these components is distributed under a proprietary license, which can be either the [Camunda Self-Managed Non-Production license](https://legal.camunda.com/#self-managed-non-production-terms) or the Camunda Self-Managed Enterprise Edition license (a copy of which you obtain when you contact Camunda). To use the software in production, [purchase the Camunda Self-Managed Enterprise Edition](https://camunda.com/platform/camunda-platform-enterprise-contact/). 

## Desktop Modeler[​](https://docs.camunda.io/docs/next/reference/licenses/#desktop-modeler)
The source code of Desktop Modeler is licensed under the MIT license as stated in the [LICENSE file](https://github.com/camunda/camunda-modeler/blob/master/LICENSE) in the root of the source code repository. This file is also shipped as LICENSE.camunda-modeler.txt with each modeler distribution.

## Camunda Connectors[​](https://docs.camunda.io/docs/next/reference/licenses/#connectors)
The Connector SDK, REST Connector, Connector Runtime Docker image, and Connectors Bundle Docker image are licensed under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0). The source code of all other Connectors provided by Camunda out of the box is licensed under the [Camunda Licence v1](https://legal.camunda.com/licensing-and-other-legal-terms#camunda-license). The compiled software is distributed under a proprietary license, which can be either the [Camunda Self-Managed Non-Production license](https://legal.camunda.com/#self-managed-non-production-terms) or the Camunda Self-Managed Enterprise Edition license (a copy of which you obtain when you contact Camunda). To use the software in production, [purchase the Camunda Self-Managed Enterprise Edition](https://camunda.com/platform/camunda-platform-enterprise-contact/).

## Web Modeler[​](https://docs.camunda.io/docs/next/reference/licenses/#web-modeler) and Console
The source code for the Web Modeler and Console is licensed to our users and customers under a proprietary license and is only available to users or customers on demand.
The compiled software of these components is distributed under a proprietary license, which can be either the [Camunda Self-Managed Non-Production license](https://legal.camunda.com/#self-managed-non-production-terms) or the Camunda Self-Managed Enterprise Edition license (a copy of which you obtain when you contact Camunda). To use the software in production, [purchase the Camunda Self-Managed Enterprise Edition](https://camunda.com/platform/camunda-platform-enterprise-contact/)..

## Camunda 8 documentation[​](https://docs.camunda.io/docs/next/reference/licenses/#camunda-8-documentation)
License information for our documentation can be found in the [LICENSE.txt](https://github.com/camunda/camunda-docs/blob/main/LICENSE.txt) of the Camunda 8 documentation repository.

**Comment by akeller** [comment]
👀 Is this shipping with 8.6 or after?

**Comment by conceptualshark** [comment]
@akeller Stuck the right label on it! this should be done this afternoon, as the copy is already written.
