### ISSUE TITLE
Document limitation of long-polling job activation via REST API

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda-docs#4375]
### Description

The Camunda Java client 8.6.0 can perform long polling job activation via the Camunda REST API.

However, due to a limitation of the embedded HTTP client, the Camunda Java client is unable to maintain a long-polling connection via REST API (i.e. HTTP 1.1) when:
* Jobs larger than the maximum message size are sent in batches
* Additional job activation requests/connections are received and closed

See [bug report](https://github.com/camunda/camunda/issues/19883) for more details.

**Comment by tmetzke** [comment]
Reopening so we can still tackle the improvement ideas detailed in https://github.com/camunda/camunda-docs/pull/4376
