### ISSUE TITLE
Document Camunda Exporter similar to ES exporter

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda-docs#4491]
Document the new Camunda Exporter created with - https://github.com/camunda/product-hub/issues/2128 - similar to our previously existing ES exporter https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/elasticsearch-exporter/

**Comment by aleksander-dytko** [comment]
@Zelldon should this be maybe under https://docs.camunda.io/docs/next/components/? As:
- this is not SM-only
- not Zeebe-only

**Comment by Zelldon** [comment]
Hey @aleksander-dytko for me first thing is to create the content (as part of this issue). I think for finding the right place the best is to let you and the docs team decide, I would say. 


In general, the documentation structure is not intuitive to me. There are often things not in places where I would expect them, so I guess this is a general thing to fix.

**Comment by Zelldon** [comment]
> this is not SM-only
> not Zeebe-only

I'm also not sure whether this is really true, as the Camunda exporter can't be used without Zeebe. It is running inside Zeebe, which is inside the C8 Platform. 

For SM it is mostly relevant, for SaaS I would expect people not care much only for a general overview maybe how the data flows.

**Comment by aleksander-dytko** [comment]
> I'm also not sure whether this is really true, as the Camunda exporter can't be used without Zeebe. It is running inside Zeebe, which is inside the C8 Platform.

I understand. I was thinking about the entire data pipeline and that it's something "in-between" Zeebe and web apps, but to your point - running in Zeebe. I think it would be good to have it as a general concept to break the component siloses even more. 

> For SM it is mostly relevant, for SaaS I would expect people not care much only for a general overview maybe how the data flows.

I see, it makes sense to me!
