### ISSUE TITLE
Document how to expose metrics in a custom exporter

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-docs#4550]
# Description

With 8.6.0, we added a new functionality where exporter authors can easily add new metrics that will be exposed alongside all the other C8 metrics (e.g. via Prometheus), using the `Context#getMeterRegistry()`.

We should document:
- That this feature exists
- What it is for
- How to use it, via an example

This should be added to the next version **and** to 8.6.x, and released as soon as possible, as it covers existing functionality.

**Comment by npepinpe** [comment]
@EuroLew - pre-assigning under the assumption this is not a big thing. Not super urgent, let's try and get it done sometime next week.

**Comment by akeller** [comment]
Added the 8.6.0, mostly for DevEx review purposes when this is PR'd.

**Comment by akeller** [comment]
@EuroLew this was closed by https://github.com/camunda/camunda-docs/pull/4551, right?

**Comment by EuroLew** [comment]
> @EuroLew this ~was~ will be closed by #4551, right?

yes
