### ISSUE TITLE
8.7 release notes link is broken

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#4587]
## Description

8.7 release notes link is broken

## How to reproduce

Open https://docs.camunda.io/docs/reference/release-notes/ (as of 11.11.), and try to click on `8.7.0` => you are redirected to the 8.6.0 notes.

## Expected behavior

8.7.0 redirects to 8.7.0.

**Comment by akeller** [comment]
This was a bug, you can find the release notes as expected via https://docs.camunda.io/docs/next/reference/release-notes/. The 8.7 release notes should only live on /next/. Closing - https://github.com/camunda/camunda-docs/pull/4592.
