### ISSUE TITLE
`Enterprise Support` statement seems to be a bit misplaced

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-docs#4615]
## Summary

`Enterprise Support` statement seems to be a bit misplaced

## How to reproduce

1. Search for `Enterprise Support`.
2. Get to this page (first result) https://docs.camunda.io/docs/next/components/zeebe/zeebe-overview/#enterprise-support-for-zeebe

=> It seems a bit off that we describe "Enterprise Support" specifically for Zeebe. Given that we offer Zeebe now together with Operate, Tasklist, Identity, ... as Camunda 8 under the [Camunda License version 1.0](https://github.com/camunda/camunda?tab=readme-ov-file#license) if would expect that we document "Enterprise Support" availability more centrally for all components.

## Suggestion for improvement

* Remove https://docs.camunda.io/docs/next/components/zeebe/zeebe-overview/#enterprise-support-for-zeebe
* Add overaching "Enterprise Support" page in https://docs.camunda.io/docs/next/reference/ - link to https://camunda.com/services/enterprise-support-guide/.
  * also see https://camunda.slack.com/archives/C0PLU0Y12/p1731915584941029

**Comment by akeller** [comment]
@MaxTru are you doing an internal/embedded "Enterprise Support" search via Algolia? Or Kapa AI?

We have a link on our [contact page](https://docs.camunda.io/contact/) (from the footer, always available). Would making that available in the sidebar fit your suggestion instead of a new, dedicated "Enterprise Support" page. We could add additional keyword metadata to this page to surface it better in searches.

**Comment by MaxTru** [comment]
> 2\. https://docs.camunda.io/docs/next/components/zeebe/zeebe-overview/#enterprise-support-for-zeebe

Hi @akeller ,

Thanks for looking at this.

I used the docs search: 
![Bildschirmfoto 2024-11-20 um 08 56 27](https://github.com/user-attachments/assets/cbb98638-3a66-471e-82e2-2958189fba12)

> We have a link on our [contact page](https://docs.camunda.io/contact/) (from the footer, always available). Would making that available in the sidebar fit your suggestion instead of a new, dedicated "Enterprise Support" page. We could add additional keyword metadata to this page to surface it better in searches.

Thanks, I did not know that. I think ensuring that this page pops up when someones searches "enterprise support" or "support" does already solve the issue. On top I would still propose to remove https://docs.camunda.io/docs/next/components/zeebe/zeebe-overview/#enterprise-support-for-zeebe, because we should treat Camunda 8 as one platform (and not have a specific support statement for one component being Zeebe).
