### ISSUE TITLE
BPMN elements render awkwardly too big on the page

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#4629]
<img width="1716" alt="image" src="https://github.com/user-attachments/assets/74c7a074-5950-4949-af7a-cfabfbe43450">

These should be consistent and smaller.

**Comment by mesellings** [comment]
@akeller I can take a look at this once the original PR is merged: https://github.com/camunda/camunda-docs/pull/4620

**Comment by mesellings** [comment]
@akeller Had some time at the end of my week, so just took a quick look - addressed in https://github.com/camunda/camunda-docs/pull/4647
