### ISSUE TITLE
No supported Java version described for the orchestration cluster

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda-docs#4685]
# Description

In [local, manual deployment page](https://docs.camunda.io/docs/next/self-managed/setup/deploy/local/manual/), we link to the supported environment when referring to the required Java version.

However, on that page, we only specify the Java version for clients, not for the server binaries. 

Please specify that for C8, with 8.7 at least, we need Java >= 21.0.3 for the server.

**Comment by conceptualshark** [comment]
@npepinpe Is this separate to the [OpenJDK version](https://github.com/camunda/camunda-docs/pull/4693) listed for individual Components, and if so, where/how would it be best called out on this page? Should this have its own heading in the SM section there? 

Thanks for any assistance!

**Comment by npepinpe** [comment]
I didn't get what you referenced in your link :smile:

**Comment by npepinpe** [comment]
This is currently what I see for local deployments:

![image](https://github.com/user-attachments/assets/4ea20513-a63d-4e1c-b994-6b85a9667d11)

Following that link leads me to a page with no information about Java version _except_ for the clients. It links back to the deployment guides, which for Kubernetes/Docker doesn't matter (since the JVM is containerized), but also links back to the manual deployment guide...which then links back to the supported environment. So it's kind of a loop :smile: 

The client JVM version is also lower than the required server JVM, so it could be misleading.

**Comment by conceptualshark** [comment]
Sorry for the broken link! The component requirements are listed individually with OpenJDK 21+:  https://docs.camunda.io/docs/next/reference/supported-environments/#component-requirements

I think there can be some confusion here with Self-Managed listed separately to Components, but I'm wondering if linking directly to the Components header would help.

**Comment by npepinpe** [comment]
No, that's correct. I have no idea how I didn't see it...I swear there was nothing! :sweat_smile: 

Anyway, this looks good enough, my bad :see_no_evil:

**Comment by npepinpe** [comment]
I think we can close this then.
