### ISSUE TITLE
Remove SaaS only badge from template generator docs

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/camunda-docs#4720]
Follow-up for https://github.com/camunda/camunda-docs/pull/4382#issuecomment-2447897950

We added the 'SaaS only' badge to the documentation, but that should be removed when this feature becomes available is SM with the next minor release (8.7)

**Comment by wollefitz** [comment]
The feature was already delivered with `8.7-alpha1` so we can already remove the badge for `next` and do not have to wait for the minor release.
