### ISSUE TITLE
Add Node SDK to SDK section

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#4782]
The fully supported [Node SDK](https://docs.camunda.io/docs/apis-tools/node-js-sdk/) needs to be added to the [SDK section](https://docs.camunda.io/docs/apis-tools/working-with-apis-tools/#sdks). It's correctly present in the sidebar, but not on the main page.

**Comment by akeller** [comment]
@christinaausley can you pick this up this week?

**Comment by christinaausley** [comment]
I'll have this done tomorrow 👍
