### ISSUE TITLE
Add how to generate GraphQL Tasklist schema 

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#480]
From Slack conversation - https://camunda-cloud.slack.com/archives/CMJ96MZAP/p1638370803001200

Use gq http://localhost:8080/graphql --introspect  to grab the schema for Tasklist (as described here)

**Comment by sdorokhova** [comment]
Accidentally noticed this issue.
Just as additional piece of information, this is how we now generate the docs (not automated): https://github.com/camunda-cloud/tasklist/wiki/Generate-GraphQL-API-docs

**Comment by akeller** [comment]
With 8.5 we moved the Tasklist GraphQL API to deprecated. I will close this issue.
