### ISSUE TITLE
Improve Task Form descriptions for C8

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-docs#806]
Task forms with C8: for C8 the form sources have to be embedded in the BPMN XML file
(https://docs.camunda.io/docs/components/modeler/bpmn/user-tasks/#user-task-forms & https://docs.camunda.io/docs/guides/utilizing-forms/ ).

I would guess this is just the current state and separate deployments (forms as JSON file separate from the BPMN) will be allowed in future - but the doc is not clear on this.

See https://docs.google.com/document/d/1yIXx4omFVbXkTmJyrr11yKXN4FG-N-_Zo2l8oQTaCdA/edit#heading=h.fibge9xpuego

**Comment by akeller** [comment]
@berndruecker are you looking for help with this or is this something you are leading? Or both? 😄

**Comment by berndruecker** [comment]
For the moment I basically wanted to park the issue as I just discovered that. Not sure if I find time to look into this week - so if somebody else can take it over I would also be happy :-)

**Comment by akeller** [comment]
@berndruecker is this still relevant?

**Comment by tmetzke** [comment]
The docs at both links have been improved with linked Camunda forms lately in 8.4.
Closing this as I think it is done. 
@berndruecker, if you disagree, please reopen and provide more detail or create a follow-up. 🙂
