### ISSUE TITLE
Move best practices to guides

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-docs#940]
As "best practices" are not a component, the guides section would be more suitable 
![image](https://user-images.githubusercontent.com/71005504/171145800-ce5cfc04-5481-42cb-abc9-71abe68845b7.png)

**Comment by akeller** [comment]
Based on V1 of the internal docs vision, this was the best place for this content at the time. We've also had some internal discussions around moving Best Practices to the top navigation header as its own section which I look to include in V2 of the docs vision.

For now, this is low priority. The majority of our traffic into docs comes from Google Search so _where_ things sit in docs isn't as relevant as SEO.

**Comment by akeller** [comment]
@christinaausley, if you'd like to do something with this issue, please do some background research first to see if this would be of value. As a best practice (ha!), I like to do this kind of exercise with any issue that's older than ~6 months. 

1. Internal anecdotal feedback - does anyone else share this feedback? Is there a better home for Best Practices? If it's moved to the Guides section, is there other restructuring work we would need to do in the Guides section? (More subsections, etc.)
2. SEO & search - how are people getting to these pages? In Google Analytics and Google Search Console, do we see any data that would help us decide where to put these? Or are they mostly coming in from external searches (and therefore _where_ they sit is less important than solid SEO)? 
3. Check with Tobias to see if he would still suggest moving these. 
4. Check with the [DevEx Vision 1.0](https://docs.google.com/presentation/d/1vd1WCkpU8VVgZ4Prmq5FQepV-GZKdv8fMoxzXPSxKGg/edit#slide=id.p). Is there anything we need to update in there about where things sit in the docs? 

If you decide not to move forward, you can close it or keep it in the inbox. Either way, leave a comment with your status update on this topic.

**Comment by akeller** [comment]
Can you bring this to the tech writer sync to collect more feedback? Or close it out as "stale"

**Comment by christinaausley** [comment]
After collecting feedback, there are no strong opinions on this issue currently. I'm going to close this for now, but we of course can reopen it if additional feedback reprioritizes this work.
