### ISSUE TITLE
Update links to examples

### ISSUE THREAD

**Issue by pihme** [camunda/camunda-docs#963]
This page contains incorrect links: https://docs.camunda.io/docs/apis-clients/java-client-examples/

* `develop` branch is now called `main`
* We plan to move the examples over to the camunda-8-examples repo: 
   * Issue in Zeebe: https://github.com/camunda/zeebe/issues/9500
   * PR in camunda-8-examples https://github.com/camunda-community-hub/camunda-8-examples/pull/3

**Comment by akeller** [comment]
My priority is the current version of the docs has the happiest path - links should be adjusted. Anything after that is a bonus when we talk about adjustments like this.

In the example repo readme I would encourage you to add a note or disclaimer that the examples in the repo may only work for the latest versions of Zeebe, particularly anything less than 1.0.

If we get feedback on the links being broken from previous versions of Zeebe, we can go in and add a short note that links to the example repo but also includes similar text saying the examples may not work for older versions. This is something the docs team can handle and I would consider it out of scope (unless you are feeling proactive, then you can tackle it too!).

**Comment by pihme** [comment]
@akeller FYI: I have removed the examples from the Zeebe repo. The link in the currently published documentation is still valid and points to a page which informs that the examples have been moved.
