### ISSUE TITLE
On prem server setup was difficult to follow

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-docs#989]
This is anecdotal feedback from the onboarding interviews so the details aren't really there.

From a quick skim through our Kubernetes + Helm and Docker docs, it looks like you need to have some amount of fundamental understanding of those technologies to get up and running, and that may be where the issue lies. How do we want to handle this assumed knowledge? 

This is also an important topic because we could be seeing a split in the granularity of the developer persona - the team or skills needed to administrate or deploy the C8 clusters is different than building a solution with C8. Both of these require development skills, but we shouldn't expect someone who builds a cloud-native app, for example, to also know the system administration skills running a cloud product or framework. 

Do we create a "guide" for deploying C8 for non-admins? Do we create a blog series on deployment skills and working with Kubernetes + Helm + Camunda? Or do we expect to hand-hold these individuals through the process or work with them to pitch SaaS as this would remove the deployment issue altogether?

**Comment by akeller** [comment]
@menski is this something Ahmed can work on? It's not as straightforward as some docs issues, but I would appreciate his thoughts on this.

Additionally, @falko is looking for instructions on how to update and backup using Helm charts, including the parameters to use for the upgrade command and how to handle credentials (some info is included [here](https://docs.camunda.io/docs/self-managed/platform-deployment/kubernetes-helm/#secrets-extraction)). This could be considered somewhat separate and I can make a separate issue, but again, is this something we can include in Ahmed's work?

**Comment by akeller** [comment]
More notes on shutting down cluster and updating:

* For a partial solution see the `update` target in https://github.com/falko/camunda-8-helm-profiles/blob/master/include/camunda.mk 
  * People copy our default chart values
    * If we change the default values, people would miss those changes
    * Help users understand their changes vs our defaults
    * Falko recommends starting with an empty chart and only changes the values he wants to change, anything else? Run with the latest defaults
    * Explicitly put the version number of Zeebe into the chart values
  * Should have update instructions for 8.1, but people may have a need to update from 1.x (this is already an issue)
    * Could we do this automated? Kubctl command for backups? Cloud provider does snapshot?

**Comment by menski** [comment]
@akeller I can talk with Ahmed about it, it is certainly in his field, but would like to clarify first the expectation.what would be your expectation here from Ahmed. Is it about giving input and help to form our strategy how to present this content, and what content. Or is it about writing that content itself?

**Comment by akeller** [comment]
Both strategy and content, but I'm happy to provide more guiding questions on the strategy side so he can focus on the content.

**Comment by conceptualshark** [comment]
@akeller I think the state of the self-managed docs might have changed some since this issue was open, but this might be worth revisiting, as I'm not sure the additional documentation has resolved some of the difficulty. I'm happy to pick this up again as a task to streamline some of our deploy and upgrade docs.

Additionally, it might be worthwhile to separate out a task from this related to surfacing SM docs in Guides - a task to accomplish a potential Get Started guide for spinning things up quickly?

**Comment by akeller** [comment]
Given all the movement on the Get Started topic, let's close this out and loop you into the work the Distribution is doing on the PDP. Can you add this as a 1:1 topic so we can find all the existing epics together?

**Comment by conceptualshark** [comment]
Marking this closed, handled by upcoming get started changes, and changes to the SM intro/Helm install + upgrade docs.
